ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      WRITE(*,*)  ' Couplings of HC_NLO_X0_UFO'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,2) 'R2_UUZ_V2 = ', R2_UUZ_V2
      WRITE(*,2) 'R2_UUZ_V5 = ', R2_UUZ_V5
      WRITE(*,2) 'GC_5 = ', GC_5
      WRITE(*,2) 'GC_3005a = ', GC_3005A
      WRITE(*,2) 'GC_3005h2 = ', GC_3005H2
      WRITE(*,2) 'GC_3005h3 = ', GC_3005H3
      WRITE(*,2) 'GC_3005h4 = ', GC_3005H4
      WRITE(*,2) 'GC_3007a = ', GC_3007A
      WRITE(*,2) 'GC_3007h2 = ', GC_3007H2
      WRITE(*,2) 'GC_3007h3 = ', GC_3007H3
      WRITE(*,2) 'GC_22 = ', GC_22
      WRITE(*,2) 'GC_23 = ', GC_23
      WRITE(*,2) 'GC_24 = ', GC_24
      WRITE(*,2) 'GC_3005h1 = ', GC_3005H1
      WRITE(*,2) 'GC_3007h1 = ', GC_3007H1
