ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      REAL*16 G
      COMMON/MP_STRONG/ G

      COMPLEX*32 GAL(2)
      COMMON/MP_WEAK/ GAL

      COMPLEX*32 MU_R
      COMMON/MP_RSCALE/ MU_R


      REAL*16 MDL_MT,MDL_MW,MDL_MZ,MDL_MTA,MDL_MB,MDL_MX0

      COMMON/MP_MASSES/ MDL_MT,MDL_MW,MDL_MZ,MDL_MTA,MDL_MB,MDL_MX0


      REAL*16 MDL_WX0,MDL_WZ,MDL_WW,MDL_WT

      COMMON/MP_WIDTHS/ MDL_WX0,MDL_WZ,MDL_WW,MDL_WT


      COMPLEX*32 R2_UUZ_V2,R2_UUZ_V5,GC_5,GC_3005A,GC_3005H2,GC_3005H3
     $ ,GC_3005H4,GC_3007A,GC_3007H2,GC_3007H3,GC_22,GC_23,GC_24
     $ ,GC_3005H1,GC_3007H1

      COMMON/MP_COUPLINGS/ R2_UUZ_V2,R2_UUZ_V5,GC_5,GC_3005A,GC_3005H2
     $ ,GC_3005H3,GC_3005H4,GC_3007A,GC_3007H2,GC_3007H3,GC_22,GC_23
     $ ,GC_24,GC_3005H1,GC_3007H1


