ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      WRITE(*,*)  ' External Params'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,*) 'MU_R = ', MU_R
      WRITE(*,*) 'aEWM1 = ', AEWM1
      WRITE(*,*) 'mdl_Gf = ', MDL_GF
      WRITE(*,*) 'aS = ', AS
      WRITE(*,*) 'mdl_ymb = ', MDL_YMB
      WRITE(*,*) 'mdl_ymt = ', MDL_YMT
      WRITE(*,*) 'mdl_ymtau = ', MDL_YMTAU
      WRITE(*,*) 'mdl_MT = ', MDL_MT
      WRITE(*,*) 'mdl_MB = ', MDL_MB
      WRITE(*,*) 'mdl_MZ = ', MDL_MZ
      WRITE(*,*) 'mdl_MTA = ', MDL_MTA
      WRITE(*,*) 'mdl_WT = ', MDL_WT
      WRITE(*,*) 'mdl_WZ = ', MDL_WZ
      WRITE(*,*) 'mdl_WW = ', MDL_WW
      WRITE(*,*) 'mdl_MX0 = ', MDL_MX0
      WRITE(*,*) 'mdl_WX0 = ', MDL_WX0
      WRITE(*,*) 'mdl_Lambda = ', MDL_LAMBDA
      WRITE(*,*) 'mdl_cosa = ', MDL_COSA
      WRITE(*,*) 'mdl_kSM = ', MDL_KSM
      WRITE(*,*) 'mdl_kHtt = ', MDL_KHTT
      WRITE(*,*) 'mdl_kAtt = ', MDL_KATT
      WRITE(*,*) 'mdl_kHbb = ', MDL_KHBB
      WRITE(*,*) 'mdl_kAbb = ', MDL_KABB
      WRITE(*,*) 'mdl_kHll = ', MDL_KHLL
      WRITE(*,*) 'mdl_kAll = ', MDL_KALL
      WRITE(*,*) 'mdl_kHaa = ', MDL_KHAA
      WRITE(*,*) 'mdl_kAaa = ', MDL_KAAA
      WRITE(*,*) 'mdl_kHza = ', MDL_KHZA
      WRITE(*,*) 'mdl_kAza = ', MDL_KAZA
      WRITE(*,*) 'mdl_kHzz = ', MDL_KHZZ
      WRITE(*,*) 'mdl_kAzz = ', MDL_KAZZ
      WRITE(*,*) 'mdl_kHww = ', MDL_KHWW
      WRITE(*,*) 'mdl_kAww = ', MDL_KAWW
      WRITE(*,*) 'mdl_kHda = ', MDL_KHDA
      WRITE(*,*) 'mdl_kHdz = ', MDL_KHDZ
      WRITE(*,*) 'mdl_kHdwR = ', MDL_KHDWR
      WRITE(*,*) 'mdl_kHdwI = ', MDL_KHDWI
      WRITE(*,*)  ' Internal Params'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,*) 'mdl_CKM11 = ', MDL_CKM11
      WRITE(*,*) 'mdl_conjg__CKM3x3 = ', MDL_CONJG__CKM3X3
      WRITE(*,*) 'mdl_conjg__CKM11 = ', MDL_CONJG__CKM11
      WRITE(*,*) 'mdl_lhv = ', MDL_LHV
      WRITE(*,*) 'mdl_CKM3x3 = ', MDL_CKM3X3
      WRITE(*,*) 'mdl_conjg__CKM33 = ', MDL_CONJG__CKM33
      WRITE(*,*) 'mdl_Ncol = ', MDL_NCOL
      WRITE(*,*) 'mdl_CA = ', MDL_CA
      WRITE(*,*) 'mdl_TF = ', MDL_TF
      WRITE(*,*) 'mdl_CF = ', MDL_CF
      WRITE(*,*) 'mdl_complexi = ', MDL_COMPLEXI
      WRITE(*,*) 'mdl_MZ__exp__2 = ', MDL_MZ__EXP__2
      WRITE(*,*) 'mdl_MZ__exp__4 = ', MDL_MZ__EXP__4
      WRITE(*,*) 'mdl_sqrt__2 = ', MDL_SQRT__2
      WRITE(*,*) 'mdl_MX0__exp__2 = ', MDL_MX0__EXP__2
      WRITE(*,*) 'mdl_cosa__exp__2 = ', MDL_COSA__EXP__2
      WRITE(*,*) 'mdl_sina = ', MDL_SINA
      WRITE(*,*) 'mdl_kHdw = ', MDL_KHDW
      WRITE(*,*) 'mdl_nb__2__exp__0_75 = ', MDL_NB__2__EXP__0_75
      WRITE(*,*) 'mdl_Ncol__exp__2 = ', MDL_NCOL__EXP__2
      WRITE(*,*) 'mdl_MB__exp__2 = ', MDL_MB__EXP__2
      WRITE(*,*) 'mdl_MT__exp__2 = ', MDL_MT__EXP__2
      WRITE(*,*) 'mdl_conjg__kHdw = ', MDL_CONJG__KHDW
      WRITE(*,*) 'mdl_aEW = ', MDL_AEW
      WRITE(*,*) 'mdl_MW = ', MDL_MW
      WRITE(*,*) 'mdl_sqrt__aEW = ', MDL_SQRT__AEW
      WRITE(*,*) 'mdl_ee = ', MDL_EE
      WRITE(*,*) 'mdl_MW__exp__2 = ', MDL_MW__EXP__2
      WRITE(*,*) 'mdl_sw2 = ', MDL_SW2
      WRITE(*,*) 'mdl_cw = ', MDL_CW
      WRITE(*,*) 'mdl_sqrt__sw2 = ', MDL_SQRT__SW2
      WRITE(*,*) 'mdl_sw = ', MDL_SW
      WRITE(*,*) 'mdl_g1 = ', MDL_G1
      WRITE(*,*) 'mdl_gw = ', MDL_GW
      WRITE(*,*) 'mdl_vev = ', MDL_VEV
      WRITE(*,*) 'mdl_vev__exp__2 = ', MDL_VEV__EXP__2
      WRITE(*,*) 'mdl_lam = ', MDL_LAM
      WRITE(*,*) 'mdl_yb = ', MDL_YB
      WRITE(*,*) 'mdl_yt = ', MDL_YT
      WRITE(*,*) 'mdl_ytau = ', MDL_YTAU
      WRITE(*,*) 'mdl_muH = ', MDL_MUH
      WRITE(*,*) 'mdl_AxialZUp = ', MDL_AXIALZUP
      WRITE(*,*) 'mdl_AxialZDown = ', MDL_AXIALZDOWN
      WRITE(*,*) 'mdl_VectorZUp = ', MDL_VECTORZUP
      WRITE(*,*) 'mdl_VectorZDown = ', MDL_VECTORZDOWN
      WRITE(*,*) 'mdl_VectorAUp = ', MDL_VECTORAUP
      WRITE(*,*) 'mdl_VectorADown = ', MDL_VECTORADOWN
      WRITE(*,*) 'mdl_VectorWmDxU = ', MDL_VECTORWMDXU
      WRITE(*,*) 'mdl_AxialWmDxU = ', MDL_AXIALWMDXU
      WRITE(*,*) 'mdl_VectorWpUxD = ', MDL_VECTORWPUXD
      WRITE(*,*) 'mdl_AxialWpUxD = ', MDL_AXIALWPUXD
      WRITE(*,*) 'mdl_I1x33 = ', MDL_I1X33
      WRITE(*,*) 'mdl_I2x33 = ', MDL_I2X33
      WRITE(*,*) 'mdl_I3x33 = ', MDL_I3X33
      WRITE(*,*) 'mdl_I4x33 = ', MDL_I4X33
      WRITE(*,*) 'mdl_Vector_tbGp = ', MDL_VECTOR_TBGP
      WRITE(*,*) 'mdl_Axial_tbGp = ', MDL_AXIAL_TBGP
      WRITE(*,*) 'mdl_Vector_tbGm = ', MDL_VECTOR_TBGM
      WRITE(*,*) 'mdl_Axial_tbGm = ', MDL_AXIAL_TBGM
      WRITE(*,*) 'mdl_ee__exp__2 = ', MDL_EE__EXP__2
      WRITE(*,*) 'mdl_gAaa = ', MDL_GAAA
      WRITE(*,*) 'mdl_cw__exp__2 = ', MDL_CW__EXP__2
      WRITE(*,*) 'mdl_gAza = ', MDL_GAZA
      WRITE(*,*) 'mdl_gHaa = ', MDL_GHAA
      WRITE(*,*) 'mdl_gHza = ', MDL_GHZA
      WRITE(*,*) 'mdl_gw__exp__2 = ', MDL_GW__EXP__2
      WRITE(*,*) 'mdl_sw__exp__2 = ', MDL_SW__EXP__2
      WRITE(*,*)  ' Internal Params evaluated point by point'
      WRITE(*,*)  ' ----------------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,*) 'mdl_sqrt__aS = ', MDL_SQRT__AS
      WRITE(*,*) 'mdl_G__exp__2 = ', MDL_G__EXP__2
      WRITE(*,*) 'mdl_G__exp__4 = ', MDL_G__EXP__4
      WRITE(*,*) 'mdl_R2MixedFactor_FIN_ = ', MDL_R2MIXEDFACTOR_FIN_
      WRITE(*,*) 'mdl_GWcft_UV_b_1EPS_ = ', MDL_GWCFT_UV_B_1EPS_
      WRITE(*,*) 'mdl_GWcft_UV_t_1EPS_ = ', MDL_GWCFT_UV_T_1EPS_
      WRITE(*,*) 'mdl_bWcft_UV_1EPS_ = ', MDL_BWCFT_UV_1EPS_
      WRITE(*,*) 'mdl_tWcft_UV_1EPS_ = ', MDL_TWCFT_UV_1EPS_
      WRITE(*,*) 'mdl_G__exp__3 = ', MDL_G__EXP__3
      WRITE(*,*) 'mdl_MU_R__exp__2 = ', MDL_MU_R__EXP__2
      WRITE(*,*) 'mdl_GWcft_UV_b_FIN_ = ', MDL_GWCFT_UV_B_FIN_
      WRITE(*,*) 'mdl_GWcft_UV_t_FIN_ = ', MDL_GWCFT_UV_T_FIN_
      WRITE(*,*) 'mdl_bWcft_UV_FIN_ = ', MDL_BWCFT_UV_FIN_
      WRITE(*,*) 'mdl_tWcft_UV_FIN_ = ', MDL_TWCFT_UV_FIN_
      WRITE(*,*) 'mdl_gAgg = ', MDL_GAGG
      WRITE(*,*) 'mdl_gHgg = ', MDL_GHGG
