/********************************************************************
* tmp/modules/FastJetDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error tmp/modules/FastJetDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableFastJetDict();
extern void G__cpp_setup_inheritanceFastJetDict();
extern void G__cpp_setup_typetableFastJetDict();
extern void G__cpp_setup_memvarFastJetDict();
extern void G__cpp_setup_globalFastJetDict();
extern void G__cpp_setup_memfuncFastJetDict();
extern void G__cpp_setup_funcFastJetDict();
extern void G__set_cpp_environmentFastJetDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__FastJetDictLN_TClass;
extern G__linked_taginfo G__FastJetDictLN_TBuffer;
extern G__linked_taginfo G__FastJetDictLN_TMemberInspector;
extern G__linked_taginfo G__FastJetDictLN_TObject;
extern G__linked_taginfo G__FastJetDictLN_TNamed;
extern G__linked_taginfo G__FastJetDictLN_vectorlEfloatcOallocatorlEfloatgRsPgR;
extern G__linked_taginfo G__FastJetDictLN_vectorlEboolcOallocatorlEboolgRsPgR;
extern G__linked_taginfo G__FastJetDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__FastJetDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__FastJetDictLN_TObjArray;
extern G__linked_taginfo G__FastJetDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__FastJetDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__FastJetDictLN_TIterator;
extern G__linked_taginfo G__FastJetDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__FastJetDictLN_TTask;
extern G__linked_taginfo G__FastJetDictLN_maplETStringcOTStringcOlesslETStringgRcOallocatorlEpairlEconstsPTStringcOTStringgRsPgRsPgR;
extern G__linked_taginfo G__FastJetDictLN_ExRootTask;
extern G__linked_taginfo G__FastJetDictLN_DelphesModule;
extern G__linked_taginfo G__FastJetDictLN_fastjet;
extern G__linked_taginfo G__FastJetDictLN_fastjetcLcLJetDefinition;
extern G__linked_taginfo G__FastJetDictLN_fastjetcLcLAreaDefinition;
extern G__linked_taginfo G__FastJetDictLN_fastjetcLcLcontrib;
extern G__linked_taginfo G__FastJetDictLN_fastjetcLcLcontribcLcLNjettinessPlugin;
extern G__linked_taginfo G__FastJetDictLN_fastjetcLcLcontribcLcLAxesDefinition;
extern G__linked_taginfo G__FastJetDictLN_fastjetcLcLcontribcLcLMeasureDefinition;
extern G__linked_taginfo G__FastJetDictLN_FastJetFinder;
extern G__linked_taginfo G__FastJetDictLN_FastJetGridMedianEstimator;
extern G__linked_taginfo G__FastJetDictLN_vectorlEfastjetcLcLGridMedianBackgroundEstimatormUcOallocatorlEfastjetcLcLGridMedianBackgroundEstimatormUgRsPgR;
extern G__linked_taginfo G__FastJetDictLN_reverse_iteratorlEvectorlEfastjetcLcLGridMedianBackgroundEstimatormUcOallocatorlEfastjetcLcLGridMedianBackgroundEstimatormUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__FastJetDictLN_PuppiContainer;
extern G__linked_taginfo G__FastJetDictLN_RunPUPPI;
extern G__linked_taginfo G__FastJetDictLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__FastJetDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
