ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      SUBROUTINE COUP1()

      IMPLICIT NONE
      INCLUDE 'model_functions.inc'

      DOUBLE PRECISION PI, ZERO
      PARAMETER  (PI=3.141592653589793D0)
      PARAMETER  (ZERO=0D0)
      INCLUDE 'input.inc'
      INCLUDE 'coupl.inc'
      REAL*16 MP__PI, MP__ZERO
      PARAMETER (MP__PI=3.1415926535897932384626433832795E0_16)
      PARAMETER (MP__ZERO=0E0_16)
      INCLUDE 'mp_input.inc'
      INCLUDE 'mp_coupl.inc'

      GC_3007A = -(MDL_COMPLEXI*MDL_SINA*MDL_KAZZ)/MDL_LAMBDA
      MP__GC_3007A = -(MP__MDL_COMPLEXI*MP__MDL_SINA*MP__MDL_KAZZ)
     $ /MP__MDL_LAMBDA
      GC_3007H2 = -(MDL_COSA*MDL_COMPLEXI*MDL_KHZZ)/MDL_LAMBDA
      MP__GC_3007H2 = -(MP__MDL_COSA*MP__MDL_COMPLEXI*MP__MDL_KHZZ)
     $ /MP__MDL_LAMBDA
      GC_3007H3 = -(MDL_COSA*MDL_COMPLEXI*MDL_KHDZ)/MDL_LAMBDA
      MP__GC_3007H3 = -(MP__MDL_COSA*MP__MDL_COMPLEXI*MP__MDL_KHDZ)
     $ /MP__MDL_LAMBDA
      GC_22 = (MDL_CW*MDL_EE*MDL_COMPLEXI)/(2.000000D+00*MDL_SW)
      MP__GC_22 = (MP__MDL_CW*MP__MDL_EE*MP__MDL_COMPLEXI)/(2.000000E
     $ +00_16*MP__MDL_SW)
      GC_23 = -(MDL_EE*MDL_COMPLEXI*MDL_SW)/(6.000000D+00*MDL_CW)
      MP__GC_23 = -(MP__MDL_EE*MP__MDL_COMPLEXI*MP__MDL_SW)/(6.000000E
     $ +00_16*MP__MDL_CW)
      GC_24 = (MDL_EE*MDL_COMPLEXI*MDL_SW)/(2.000000D+00*MDL_CW)
      MP__GC_24 = (MP__MDL_EE*MP__MDL_COMPLEXI*MP__MDL_SW)/(2.000000E
     $ +00_16*MP__MDL_CW)
      GC_3007H1 = MDL_COSA*MDL_EE__EXP__2*MDL_COMPLEXI*MDL_KSM*MDL_VEV
     $ +(MDL_COSA*MDL_CW__EXP__2*MDL_EE__EXP__2*MDL_COMPLEXI*MDL_KSM
     $ *MDL_VEV)/(2.000000D+00*MDL_SW__EXP__2)+(MDL_COSA
     $ *MDL_EE__EXP__2*MDL_COMPLEXI*MDL_KSM*MDL_SW__EXP__2*MDL_VEV)
     $ /(2.000000D+00*MDL_CW__EXP__2)
      MP__GC_3007H1 = MP__MDL_COSA*MP__MDL_EE__EXP__2*MP__MDL_COMPLEXI
     $ *MP__MDL_KSM*MP__MDL_VEV+(MP__MDL_COSA*MP__MDL_CW__EXP__2
     $ *MP__MDL_EE__EXP__2*MP__MDL_COMPLEXI*MP__MDL_KSM*MP__MDL_VEV)
     $ /(2.000000E+00_16*MP__MDL_SW__EXP__2)+(MP__MDL_COSA
     $ *MP__MDL_EE__EXP__2*MP__MDL_COMPLEXI*MP__MDL_KSM
     $ *MP__MDL_SW__EXP__2*MP__MDL_VEV)/(2.000000E+00_16
     $ *MP__MDL_CW__EXP__2)
      END
