C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     Identity(2,1)*Metric(1003,2003)
C     
      SUBROUTINE FFT1_2(F1, T3, COUP, M2, W2,F2)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 F2(6)
      REAL*8 P2(0:3)
      REAL*8 W2
      COMPLEX*16 F1(*)
      REAL*8 M2
      COMPLEX*16 DENOM
      COMPLEX*16 TMP4
      COMPLEX*16 T3(*)
      COMPLEX*16 COUP
      F2(1) = +F1(1)+T3(1)
      F2(2) = +F1(2)+T3(2)
      P2(0) = -DBLE(F2(1))
      P2(1) = -DBLE(F2(2))
      P2(2) = -DIMAG(F2(2))
      P2(3) = -DIMAG(F2(1))
      TMP4 = (T3(3)-T3(8)-T3(13)-T3(18))
      DENOM = COUP/(P2(0)**2-P2(1)**2-P2(2)**2-P2(3)**2 - M2 * (M2 -CI
     $ * W2))
      F2(3)= DENOM*CI * TMP4*(F1(5)*(P2(0)-P2(3))+(F1(6)*(+CI*(P2(2))
     $ -P2(1))+F1(3)*M2))
      F2(4)= DENOM*(-CI )* TMP4*(F1(5)*(P2(1)+CI*(P2(2)))+(F1(6)*(-1D0)
     $ *(P2(0)+P2(3))-F1(4)*M2))
      F2(5)= DENOM*(-CI )* TMP4*(F1(3)*(-1D0)*(P2(0)+P2(3))+(F1(4)*(
     $ +CI*(P2(2))-P2(1))-F1(5)*M2))
      F2(6)= DENOM*CI * TMP4*(F1(3)*(P2(1)+CI*(P2(2)))+(F1(4)*(P2(0)
     $ -P2(3))+F1(6)*M2))
      END


C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     Identity(2,1)*Metric(1003,2003)
C     
      SUBROUTINE FFT1_2_2(F1, T3, COUP1, COUP2, M2, W2,F2)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 F2(6)
      COMPLEX*16 FTMP(6)
      COMPLEX*16 COUP2
      REAL*8 P2(0:3)
      REAL*8 W2
      COMPLEX*16 F1(*)
      REAL*8 M2
      COMPLEX*16 DENOM
      COMPLEX*16 COUP1
      COMPLEX*16 T3(*)
      INTEGER*4 I
      CALL FFT1_2(F1,T3,COUP1,M2,W2,F2)
      CALL FFT2_2(F1,T3,COUP2,M2,W2,FTMP)
      DO I = 3, 6
        F2(I) = F2(I) + FTMP(I)
      ENDDO
      END


