C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     Identity(2,1)*Metric(1003,2003)
C     
      SUBROUTINE FFT1_1(F2, T3, COUP, M1, W1,F1)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 F2(*)
      REAL*8 P1(0:3)
      REAL*8 M1
      REAL*8 W1
      COMPLEX*16 F1(6)
      COMPLEX*16 DENOM
      COMPLEX*16 TMP4
      COMPLEX*16 T3(*)
      COMPLEX*16 COUP
      F1(1) = +F2(1)+T3(1)
      F1(2) = +F2(2)+T3(2)
      P1(0) = -DBLE(F1(1))
      P1(1) = -DBLE(F1(2))
      P1(2) = -DIMAG(F1(2))
      P1(3) = -DIMAG(F1(1))
      TMP4 = (T3(3)-T3(8)-T3(13)-T3(18))
      DENOM = COUP/(P1(0)**2-P1(1)**2-P1(2)**2-P1(3)**2 - M1 * (M1 -CI
     $ * W1))
      F1(3)= DENOM*(-CI )* TMP4*(F2(5)*(P1(0)+P1(3))+(F2(6)*(P1(1)+CI
     $ *(P1(2)))-F2(3)*M1))
      F1(4)= DENOM*CI * TMP4*(F2(5)*(+CI*(P1(2))-P1(1))+(F2(6)*(P1(3)
     $ -P1(0))+F2(4)*M1))
      F1(5)= DENOM*CI * TMP4*(F2(3)*(P1(3)-P1(0))+(F2(4)*(P1(1)+CI
     $ *(P1(2)))+F2(5)*M1))
      F1(6)= DENOM*(-CI )* TMP4*(F2(3)*(+CI*(P1(2))-P1(1))+(F2(4)
     $ *(P1(0)+P1(3))-F2(6)*M1))
      END


C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     Identity(2,1)*Metric(1003,2003)
C     
      SUBROUTINE FFT1_2_1(F2, T3, COUP1, COUP2, M1, W1,F1)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 F2(*)
      REAL*8 P1(0:3)
      REAL*8 M1
      REAL*8 W1
      COMPLEX*16 F1(6)
      COMPLEX*16 COUP1
      COMPLEX*16 DENOM
      COMPLEX*16 COUP2
      COMPLEX*16 T3(*)
      INTEGER*4 I
      COMPLEX*16 FTMP(6)
      CALL FFT1_1(F2,T3,COUP1,M1,W1,F1)
      CALL FFT2_1(F2,T3,COUP2,M1,W1,FTMP)
      DO I = 3, 6
        F1(I) = F1(I) + FTMP(I)
      ENDDO
      END


