C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     Metric(1,2)
C     
      SUBROUTINE MP_VVS1_2(V1, S3, COUP, M2, W2,V2)
      IMPLICIT NONE
      COMPLEX*32 CI
      PARAMETER (CI=(0Q0,1Q0))
      COMPLEX*32 V2(8)
      COMPLEX*32 DENOM
      COMPLEX*32 S3(*)
      REAL*16 W2
      COMPLEX*32 P2(0:3)
      REAL*16 M2
      COMPLEX*32 TMP5
      REAL*16 OM2
      COMPLEX*32 COUP
      COMPLEX*32 V1(*)
      OM2 = 0Q0
      IF (M2.NE.0Q0) OM2=1Q0/M2**2
      V2(1) = +V1(1)+S3(1)
      V2(2) = +V1(2)+S3(2)
      V2(3) = +V1(3)+S3(3)
      V2(4) = +V1(4)+S3(4)
      P2(0) = -V2(1)
      P2(1) = -V2(2)
      P2(2) = -V2(3)
      P2(3) = -V2(4)
      TMP5 = (P2(0)*V1(5)-P2(1)*V1(6)-P2(2)*V1(7)-P2(3)*V1(8))
      DENOM = COUP/(P2(0)**2-P2(1)**2-P2(2)**2-P2(3)**2 - M2 * (M2 -CI
     $ * W2))
      V2(5)= DENOM*S3(5)*(-CI*(V1(5))+CI*(P2(0)*OM2*TMP5))
      V2(6)= DENOM*S3(5)*(-CI*(V1(6))+CI*(P2(1)*OM2*TMP5))
      V2(7)= DENOM*S3(5)*(-CI*(V1(7))+CI*(P2(2)*OM2*TMP5))
      V2(8)= DENOM*S3(5)*(-CI*(V1(8))+CI*(P2(3)*OM2*TMP5))
      END


