C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
Coup(1) * (Epsilon(1,2,-1,-2)*P(-1,1)*P(-2,2)) + Coup(2) * (Metric(1,2)) + Coup(3) * (P(1,2)*P(2,1) - P(-1,1)*P(-1,2)*Metric(1,2)) + Coup(4) * (P(1,1)*P(2,1) - P(-1,1)*P(-1,1)*Metric(1,2) + P(1,2)*P(2,2) - P(-1,2)*P(-1,2)*Metric(1,2))
C     
      SUBROUTINE VVS10_1_2_13_2(V1, S3, COUP1, COUP2, COUP3, COUP4, M2
     $ , W2,V2)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 V2(8)
      COMPLEX*16 DENOM
      COMPLEX*16 S3(*)
      COMPLEX*16 TMP1
      COMPLEX*16 COUP2
      REAL*8 W2
      COMPLEX*16 P2(0:3)
      COMPLEX*16 COUP1
      COMPLEX*16 TMP4
      COMPLEX*16 TMP5
      COMPLEX*16 P1(0:3)
      REAL*8 OM2
      COMPLEX*16 COUP4
      REAL*8 M2
      COMPLEX*16 COUP3
      COMPLEX*16 V1(*)
      COMPLEX*16 TMP3
      COMPLEX*16 TMP8
      P1(0) = V1(1)
      P1(1) = V1(2)
      P1(2) = V1(3)
      P1(3) = V1(4)
      OM2 = 0D0
      IF (M2.NE.0D0) OM2=1D0/M2**2
      V2(1) = +V1(1)+S3(1)
      V2(2) = +V1(2)+S3(2)
      V2(3) = +V1(3)+S3(3)
      V2(4) = +V1(4)+S3(4)
      P2(0) = -V2(1)
      P2(1) = -V2(2)
      P2(2) = -V2(3)
      P2(3) = -V2(4)
      TMP5 = (P2(0)*V1(5)-P2(1)*V1(6)-P2(2)*V1(7)-P2(3)*V1(8))
      TMP4 = (P1(0)*P2(0)-P1(1)*P2(1)-P1(2)*P2(2)-P1(3)*P2(3))
      TMP1 = (P1(0)*V1(5)-P1(1)*V1(6)-P1(2)*V1(7)-P1(3)*V1(8))
      TMP8 = (P2(0)*P2(0)-P2(1)*P2(1)-P2(2)*P2(2)-P2(3)*P2(3))
      TMP3 = (P1(0)*P1(0)-P1(1)*P1(1)-P1(2)*P1(2)-P1(3)*P1(3))
      DENOM = 1D0/(P2(0)**2-P2(1)**2-P2(2)**2-P2(3)**2 - M2 * (M2 -CI*
     $  W2))
      V2(5)= DENOM*CI * S3(5)*(COUP1*(P1(1)*(P2(2)*V1(8)-P2(3)*V1(7))
     $ +(P1(2)*(P2(3)*V1(6)-P2(1)*V1(8))+P1(3)*(P2(1)*V1(7)-P2(2)*V1(6)
     $ )))+(COUP4*(P2(0)*(TMP5*(-1D0)*(TMP3*OM2+ 1D0)+TMP1*OM2*TMP4)
     $ +(V1(5)*(TMP3+TMP8)-P1(0)*TMP1))+(V1(5)*(TMP4*COUP3-COUP2)+TMP5
     $ *(P2(0)*OM2*COUP2-P1(0)*COUP3))))
      V2(6)= DENOM*(-CI )* S3(5)*(COUP1*(P1(0)*(P2(3)*V1(7)-P2(2)*V1(8)
     $ )+(P1(2)*(P2(0)*V1(8)-P2(3)*V1(5))+P1(3)*(P2(2)*V1(5)-P2(0)
     $ *V1(7))))+(COUP4*(P2(1)*(TMP5*(TMP3*OM2+ 1D0)-TMP1*OM2*TMP4)
     $ +(V1(6)*(-1D0)*(TMP3+TMP8)+P1(1)*TMP1))+(V1(6)*(COUP2-TMP4
     $ *COUP3)+TMP5*(P1(1)*COUP3-P2(1)*OM2*COUP2))))
      V2(7)= DENOM*(-CI )* S3(5)*(COUP1*(P1(0)*(P2(1)*V1(8)-P2(3)*V1(6)
     $ )+(P1(1)*(P2(3)*V1(5)-P2(0)*V1(8))+P1(3)*(P2(0)*V1(6)-P2(1)
     $ *V1(5))))+(COUP4*(P2(2)*(TMP5*(TMP3*OM2+ 1D0)-TMP1*OM2*TMP4)
     $ +(V1(7)*(-1D0)*(TMP3+TMP8)+P1(2)*TMP1))+(V1(7)*(COUP2-TMP4
     $ *COUP3)+TMP5*(P1(2)*COUP3-P2(2)*OM2*COUP2))))
      V2(8)= DENOM*(-CI )* S3(5)*(COUP1*(P1(0)*(P2(2)*V1(6)-P2(1)*V1(7)
     $ )+(P1(1)*(P2(0)*V1(7)-P2(2)*V1(5))+P1(2)*(P2(1)*V1(5)-P2(0)
     $ *V1(6))))+(COUP4*(P2(3)*(TMP5*(TMP3*OM2+ 1D0)-TMP1*OM2*TMP4)
     $ +(V1(8)*(-1D0)*(TMP3+TMP8)+P1(3)*TMP1))+(V1(8)*(COUP2-TMP4
     $ *COUP3)+TMP5*(P1(3)*COUP3-P2(3)*OM2*COUP2))))
      END


