ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      SUBROUTINE COUP2()

      IMPLICIT NONE
      INCLUDE 'model_functions.inc'

      DOUBLE PRECISION PI, ZERO
      PARAMETER  (PI=3.141592653589793D0)
      PARAMETER  (ZERO=0D0)
      INCLUDE 'input.inc'
      INCLUDE 'coupl.inc'
      GC_101 = -((MDL_CA*MDL_COMPLEXI*MDL_KHBB*MDL_YB)/MDL_SQRT__2)
      GC_102 = (MDL_KABB*MDL_SA*MDL_YB)/MDL_SQRT__2
      GC_105 = -((MDL_CA*MDL_COMPLEXI*MDL_KHLL*MDL_YTAU)/MDL_SQRT__2)
      GC_106 = (MDL_KALL*MDL_SA*MDL_YTAU)/MDL_SQRT__2
      GC_107 = (MDL_EE*MDL_COMPLEXI*MDL_CONJG__CKM1X1)/(MDL_SW
     $ *MDL_SQRT__2)
      GC_108 = (MDL_EE*MDL_COMPLEXI*MDL_CONJG__CKM1X2)/(MDL_SW
     $ *MDL_SQRT__2)
      GC_109 = (MDL_EE*MDL_COMPLEXI*MDL_CONJG__CKM2X1)/(MDL_SW
     $ *MDL_SQRT__2)
      GC_110 = (MDL_EE*MDL_COMPLEXI*MDL_CONJG__CKM2X2)/(MDL_SW
     $ *MDL_SQRT__2)
      GC_35 = -((MDL_COMPLEXI*MDL_KG)/MDL_LAMBDA)
      GC_38 = -((MDL_CA*MDL_COMPLEXI*MDL_KHDA)/MDL_LAMBDA)
      GC_39 = -((MDL_CA*MDL_COMPLEXI*MDL_KHDW)/MDL_LAMBDA)
      GC_40 = -((MDL_CA*MDL_COMPLEXI*MDL_KHDZ)/MDL_LAMBDA)
      GC_41 = -((MDL_CA*MDL_COMPLEXI*MDL_KHWW)/MDL_LAMBDA)
      GC_42 = -((MDL_CA*MDL_COMPLEXI*MDL_KHZZ)/MDL_LAMBDA)
      GC_43 = (MDL_COMPLEXI*MDL_KL)/(4.000000D+00*MDL_LAMBDA)
      GC_45 = (MDL_COMPLEXI*MDL_KQ)/(4.000000D+00*MDL_LAMBDA)
      GC_49 = (MDL_COMPLEXI*MDL_KQ3)/(4.000000D+00*MDL_LAMBDA)
      GC_56 = -((MDL_COMPLEXI*MDL_KQ3*MDL_MB)/MDL_LAMBDA)
      GC_58 = -((MDL_COMPLEXI*MDL_KL*MDL_MTA)/MDL_LAMBDA)
      GC_67 = (MDL_COMPLEXI*MDL_KAWW*MDL_SA)/MDL_LAMBDA
      GC_68 = (MDL_COMPLEXI*MDL_KAZZ*MDL_SA)/(2.000000D+00*MDL_LAMBDA)
      GC_111 = -((MDL_CA*MDL_COMPLEXI*MDL_CONJG__KHDW)/MDL_LAMBDA)
      END
