C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     -4*Epsilon(1,2,-1,-2)*P(-2,2)*P(-1,1) + 4*Epsilon(1,2,-1,-2)*P(-2
C     ,1)*P(-1,2)
C     
      SUBROUTINE VVSS1_3(V1, V2, S4, COUP, M3, W3,S3)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 V2(*)
      COMPLEX*16 S3(3)
      COMPLEX*16 COUP
      REAL*8 P1(0:3)
      REAL*8 W3
      REAL*8 P2(0:3)
      COMPLEX*16 TMP17
      REAL*8 P3(0:3)
      REAL*8 M3
      COMPLEX*16 DENOM
      COMPLEX*16 S4(*)
      COMPLEX*16 V1(*)
      COMPLEX*16 TMP18
      P1(0) = DBLE(V1(1))
      P1(1) = DBLE(V1(2))
      P1(2) = DIMAG(V1(2))
      P1(3) = DIMAG(V1(1))
      P2(0) = DBLE(V2(1))
      P2(1) = DBLE(V2(2))
      P2(2) = DIMAG(V2(2))
      P2(3) = DIMAG(V2(1))
      S3(1) = +V1(1)+V2(1)+S4(1)
      S3(2) = +V1(2)+V2(2)+S4(2)
      P3(0) = -DBLE(S3(1))
      P3(1) = -DBLE(S3(2))
      P3(2) = -DIMAG(S3(2))
      P3(3) = -DIMAG(S3(1))
      TMP17 = (-1D0)*(P1(0)*(P2(1)*(V2(5)*V1(6)-V2(6)*V1(5))+(P2(2)
     $ *(V2(6)*V1(4)-V2(4)*V1(6))+P2(3)*(V2(4)*V1(5)-V2(5)*V1(4))))
     $ +(P1(1)*(P2(0)*(V2(6)*V1(5)-V2(5)*V1(6))+(P2(2)*(V2(3)*V1(6)
     $ -V2(6)*V1(3))+P2(3)*(V2(5)*V1(3)-V2(3)*V1(5))))+(P1(2)*(P2(0)
     $ *(V2(4)*V1(6)-V2(6)*V1(4))+(P2(1)*(V2(6)*V1(3)-V2(3)*V1(6))
     $ +P2(3)*(V2(3)*V1(4)-V2(4)*V1(3))))+P1(3)*(P2(0)*(V2(5)*V1(4)
     $ -V2(4)*V1(5))+(P2(1)*(V2(3)*V1(5)-V2(5)*V1(3))+P2(2)*(V2(4)
     $ *V1(3)-V2(3)*V1(4)))))))
      TMP18 = (-1D0)*(P1(0)*(P2(1)*(V2(6)*V1(5)-V2(5)*V1(6))+(P2(2)
     $ *(V2(4)*V1(6)-V2(6)*V1(4))+P2(3)*(V2(5)*V1(4)-V2(4)*V1(5))))
     $ +(P1(1)*(P2(0)*(V2(5)*V1(6)-V2(6)*V1(5))+(P2(2)*(V2(6)*V1(3)
     $ -V2(3)*V1(6))+P2(3)*(V2(3)*V1(5)-V2(5)*V1(3))))+(P1(2)*(P2(0)
     $ *(V2(6)*V1(4)-V2(4)*V1(6))+(P2(1)*(V2(3)*V1(6)-V2(6)*V1(3))
     $ +P2(3)*(V2(4)*V1(3)-V2(3)*V1(4))))+P1(3)*(P2(0)*(V2(4)*V1(5)
     $ -V2(5)*V1(4))+(P2(1)*(V2(5)*V1(3)-V2(3)*V1(5))+P2(2)*(V2(3)
     $ *V1(4)-V2(4)*V1(3)))))))
      DENOM = COUP/(P3(0)**2-P3(1)**2-P3(2)**2-P3(3)**2 - M3 * (M3 -CI
     $ * W3))
      S3(3)= DENOM*4D0 * S4(3)*(-CI*(TMP17)+CI*(TMP18))
      END


C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     -4*Epsilon(1,2,-1,-2)*P(-2,2)*P(-1,1) + 4*Epsilon(1,2,-1,-2)*P(-2
C     ,1)*P(-1,2)
C     
      SUBROUTINE VVSS1_3_3(V1, V2, S4, COUP1, COUP2, M3, W3,S3)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 V2(*)
      COMPLEX*16 COUP2
      COMPLEX*16 S3(3)
      REAL*8 P1(0:3)
      REAL*8 W3
      REAL*8 P2(0:3)
      REAL*8 P3(0:3)
      REAL*8 M3
      COMPLEX*16 COUP1
      COMPLEX*16 DENOM
      COMPLEX*16 STMP(3)
      INTEGER*4 I
      COMPLEX*16 S4(*)
      COMPLEX*16 V1(*)
      CALL VVSS1_3(V1,V2,S4,COUP1,M3,W3,S3)
      CALL VVSS3_3(V1,V2,S4,COUP2,M3,W3,STMP)
      DO I = 3, 3
        S3(I) = S3(I) + STMP(I)
      ENDDO
      END


