C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     P(1003,2)*P(2003,1)*Metric(1,2) + P(1003,1)*P(2003,2)*Metric(1,2)
C      - P(2,1)*P(2003,2)*Metric(1,1003) - P(2,2)*P(2003,2)*Metric(1,10
C     03) - P(2,1)*P(1003,2)*Metric(1,2003) - P(2,2)*P(1003,2)*Metric(1
C     ,2003) - P(1,1)*P(2003,1)*Metric(2,1003) - P(1,2)*P(2003,1)*Metri
C     c(2,1003) + P(-1,1)*P(-1,2)*Metric(1,2003)*Metric(2,1003) -
C      P(1,1)*P(1003,1)*Metric(2,2003) - P(1,2)*P(1003,1)*Metric(2,2003)
C      + P(-1,1)*P(-1,2)*Metric(1,1003)*Metric(2,2003) +
C      P(1,1)*P(2,1)*Metric(1003,2003) + P(1,2)*P(2,1)*Metric(1003,2003)
C      + P(1,1)*P(2,2)*Metric(1003,2003) + P(1,2)*P(2,2)*Metric(1003,20
C     03) - P(-1,1)*P(-1,2)*Metric(1,2)*Metric(1003,2003)
C     
      SUBROUTINE VVT3_3(V1, V2, COUP, M3, W3,T3)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 TMP1
      COMPLEX*16 TMP10
      REAL*8 P3(0:3)
      COMPLEX*16 TMP14
      COMPLEX*16 T3(18)
      COMPLEX*16 COUP
      COMPLEX*16 TMP9
      COMPLEX*16 TMP2
      COMPLEX*16 TMP11
      REAL*8 P2(0:3)
      COMPLEX*16 TMP15
      REAL*8 OM3
      COMPLEX*16 TMP3
      COMPLEX*16 V2(*)
      COMPLEX*16 TMP12
      REAL*8 P1(0:3)
      REAL*8 W3
      COMPLEX*16 DENOM
      COMPLEX*16 V1(*)
      COMPLEX*16 TMP13
      COMPLEX*16 TMP0
      REAL*8 M3
      P1(0) = DBLE(V1(1))
      P1(1) = DBLE(V1(2))
      P1(2) = DIMAG(V1(2))
      P1(3) = DIMAG(V1(1))
      P2(0) = DBLE(V2(1))
      P2(1) = DBLE(V2(2))
      P2(2) = DIMAG(V2(2))
      P2(3) = DIMAG(V2(1))
      OM3 = 0D0
      IF (M3.NE.0D0) OM3=1D0/M3**2
      T3(1) = +V1(1)+V2(1)
      T3(2) = +V1(2)+V2(2)
      P3(0) = -DBLE(T3(1))
      P3(1) = -DBLE(T3(2))
      P3(2) = -DIMAG(T3(2))
      P3(3) = -DIMAG(T3(1))
      TMP1 = (V1(3)*P2(0)-V1(4)*P2(1)-V1(5)*P2(2)-V1(6)*P2(3))
      TMP0 = (V2(3)*P1(0)-V2(4)*P1(1)-V2(5)*P1(2)-V2(6)*P1(3))
      TMP9 = (P1(0)*P3(0)-P1(1)*P3(1)-P1(2)*P3(2)-P1(3)*P3(3))
      TMP3 = (P1(0)*P2(0)-P1(1)*P2(1)-P1(2)*P2(2)-P1(3)*P2(3))
      TMP15 = (P3(0)*P3(0)-P3(1)*P3(1)-P3(2)*P3(2)-P3(3)*P3(3))
      TMP14 = (V2(3)*P3(0)-V2(4)*P3(1)-V2(5)*P3(2)-V2(6)*P3(3))
      TMP2 = (V2(3)*V1(3)-V2(4)*V1(4)-V2(5)*V1(5)-V2(6)*V1(6))
      TMP11 = (V1(3)*P3(0)-V1(4)*P3(1)-V1(5)*P3(2)-V1(6)*P3(3))
      TMP10 = (P2(0)*P3(0)-P2(1)*P3(1)-P2(2)*P3(2)-P2(3)*P3(3))
      TMP13 = (P1(0)*V1(3)-P1(1)*V1(4)-P1(2)*V1(5)-P1(3)*V1(6))
      TMP12 = (V2(3)*P2(0)-V2(4)*P2(1)-V2(5)*P2(2)-V2(6)*P2(3))
      DENOM = COUP/(P3(0)**2-P3(1)**2-P3(2)**2-P3(3)**2 - M3 * (M3 -CI
     $ * W3))
      T3(3)= DENOM*2D0*(OM3*(P3(0)*(P3(0)*(OM3*(TMP15*(TMP0*1D0/3D0*(
     $ +CI*(TMP13+TMP1))+(TMP12*1D0/3D0*(+CI*(TMP13+TMP1))-1D0/3D0 *
     $  CI*(TMP2*TMP3)))+(TMP10*(TMP11*(-2D0/3D0)*(+CI*(TMP0+TMP12))
     $ +2D0/3D0 * CI*(TMP2*TMP9))+TMP14*(TMP9*(-2D0/3D0)*(+CI*(TMP13
     $ +TMP1))+2D0/3D0 * CI*(TMP3*TMP11))))+(TMP0*(-2D0/3D0)*(+3D0/2D0
     $  * CI*(TMP1)+CI*(TMP13))+(TMP12*(-2D0/3D0)*(+1D0/2D0 * CI
     $ *(TMP13)+CI*(TMP1))+1D0/1D0 * CI*(TMP2*TMP3))))+(P1(0)*(TMP14*(
     $ +CI*(TMP13+TMP1))-CI*(TMP2*TMP10))+(P2(0)*(TMP11*(+CI*(TMP0
     $ +TMP12))-CI*(TMP2*TMP9))+(V1(3)*(TMP10*(+CI*(TMP0+TMP12))-CI
     $ *(TMP3*TMP14))+V2(3)*(TMP9*(+CI*(TMP13+TMP1))-CI*(TMP3*TMP11))))
     $ ))+(TMP15*(TMP0*1D0/6D0*(+CI*(TMP13+TMP1))+(TMP12*1D0/6D0*(+CI
     $ *(TMP13+TMP1))-1D0/6D0 * CI*(TMP2*TMP3)))+(TMP10*(TMP11*(-1D0
     $ /3D0)*(+CI*(TMP0+TMP12))+1D0/3D0 * CI*(TMP2*TMP9))+TMP14*(TMP9
     $ *(-1D0/3D0)*(+CI*(TMP13+TMP1))+1D0/3D0 * CI*(TMP3*TMP11)))))
     $ +(P1(0)*(V2(3)*(-1D0)*(+CI*(TMP13+TMP1))+CI*(P2(0)*TMP2))+(V1(3)
     $ *(P2(0)*(-1D0)*(+CI*(TMP0+TMP12))+CI*(V2(3)*TMP3))+(TMP0*1D0
     $ /2D0*(+CI*(TMP1)+1D0/3D0 * CI*(TMP13))+(-1D0/2D0 * CI*(TMP2
     $ *TMP3)+TMP12*1D0/6D0*(-1D0/1D0 * CI*(TMP13)+CI*(TMP1)))))))
      T3(4)= DENOM*(OM3*(P3(0)*(P3(1)*(OM3*(TMP15*(TMP0*2D0/3D0*(+CI
     $ *(TMP13+TMP1))+(TMP12*2D0/3D0*(+CI*(TMP13+TMP1))-2D0/3D0 * CI
     $ *(TMP2*TMP3)))+(TMP10*(TMP11*(-4D0/3D0)*(+CI*(TMP0+TMP12))+4D0
     $ /3D0 * CI*(TMP2*TMP9))+TMP14*(TMP9*(-4D0/3D0)*(+CI*(TMP13+TMP1))
     $ +4D0/3D0 * CI*(TMP3*TMP11))))+(TMP0*(-4D0/3D0)*(+3D0/2D0 * CI
     $ *(TMP1)+CI*(TMP13))+(TMP12*(-4D0/3D0)*(+1D0/2D0 * CI*(TMP13)+CI
     $ *(TMP1))+2D0/1D0 * CI*(TMP2*TMP3))))+(P1(1)*(TMP14*(+CI*(TMP13
     $ +TMP1))-CI*(TMP2*TMP10))+(P2(1)*(TMP11*(+CI*(TMP0+TMP12))-CI
     $ *(TMP2*TMP9))+(V1(4)*(TMP10*(+CI*(TMP0+TMP12))-CI*(TMP3*TMP14))
     $ +V2(4)*(TMP9*(+CI*(TMP13+TMP1))-CI*(TMP3*TMP11))))))+P3(1)
     $ *(P1(0)*(TMP14*(+CI*(TMP13+TMP1))-CI*(TMP2*TMP10))+(P2(0)
     $ *(TMP11*(+CI*(TMP0+TMP12))-CI*(TMP2*TMP9))+(V1(3)*(TMP10*(+CI
     $ *(TMP0+TMP12))-CI*(TMP3*TMP14))+V2(3)*(TMP9*(+CI*(TMP13+TMP1))
     $ -CI*(TMP3*TMP11))))))+(P1(0)*(V2(4)*(-1D0)*(+CI*(TMP13+TMP1))
     $ +CI*(P2(1)*TMP2))+(P1(1)*(V2(3)*(-1D0)*(+CI*(TMP13+TMP1))+CI
     $ *(P2(0)*TMP2))+(V1(3)*(P2(1)*(-1D0)*(+CI*(TMP0+TMP12))+CI*(V2(4)
     $ *TMP3))+V1(4)*(P2(0)*(-1D0)*(+CI*(TMP0+TMP12))+CI*(V2(3)*TMP3)))
     $ )))
      T3(5)= DENOM*(OM3*(P3(0)*(P3(2)*(OM3*(TMP15*(TMP0*2D0/3D0*(+CI
     $ *(TMP13+TMP1))+(TMP12*2D0/3D0*(+CI*(TMP13+TMP1))-2D0/3D0 * CI
     $ *(TMP2*TMP3)))+(TMP10*(TMP11*(-4D0/3D0)*(+CI*(TMP0+TMP12))+4D0
     $ /3D0 * CI*(TMP2*TMP9))+TMP14*(TMP9*(-4D0/3D0)*(+CI*(TMP13+TMP1))
     $ +4D0/3D0 * CI*(TMP3*TMP11))))+(TMP0*(-4D0/3D0)*(+3D0/2D0 * CI
     $ *(TMP1)+CI*(TMP13))+(TMP12*(-4D0/3D0)*(+1D0/2D0 * CI*(TMP13)+CI
     $ *(TMP1))+2D0/1D0 * CI*(TMP2*TMP3))))+(P1(2)*(TMP14*(+CI*(TMP13
     $ +TMP1))-CI*(TMP2*TMP10))+(P2(2)*(TMP11*(+CI*(TMP0+TMP12))-CI
     $ *(TMP2*TMP9))+(V1(5)*(TMP10*(+CI*(TMP0+TMP12))-CI*(TMP3*TMP14))
     $ +V2(5)*(TMP9*(+CI*(TMP13+TMP1))-CI*(TMP3*TMP11))))))+P3(2)
     $ *(P1(0)*(TMP14*(+CI*(TMP13+TMP1))-CI*(TMP2*TMP10))+(P2(0)
     $ *(TMP11*(+CI*(TMP0+TMP12))-CI*(TMP2*TMP9))+(V1(3)*(TMP10*(+CI
     $ *(TMP0+TMP12))-CI*(TMP3*TMP14))+V2(3)*(TMP9*(+CI*(TMP13+TMP1))
     $ -CI*(TMP3*TMP11))))))+(P1(0)*(V2(5)*(-1D0)*(+CI*(TMP13+TMP1))
     $ +CI*(P2(2)*TMP2))+(P1(2)*(V2(3)*(-1D0)*(+CI*(TMP13+TMP1))+CI
     $ *(P2(0)*TMP2))+(V1(3)*(P2(2)*(-1D0)*(+CI*(TMP0+TMP12))+CI*(V2(5)
     $ *TMP3))+V1(5)*(P2(0)*(-1D0)*(+CI*(TMP0+TMP12))+CI*(V2(3)*TMP3)))
     $ )))
      T3(6)= DENOM*(OM3*(P3(0)*(P3(3)*(OM3*(TMP15*(TMP0*2D0/3D0*(+CI
     $ *(TMP13+TMP1))+(TMP12*2D0/3D0*(+CI*(TMP13+TMP1))-2D0/3D0 * CI
     $ *(TMP2*TMP3)))+(TMP10*(TMP11*(-4D0/3D0)*(+CI*(TMP0+TMP12))+4D0
     $ /3D0 * CI*(TMP2*TMP9))+TMP14*(TMP9*(-4D0/3D0)*(+CI*(TMP13+TMP1))
     $ +4D0/3D0 * CI*(TMP3*TMP11))))+(TMP0*(-4D0/3D0)*(+3D0/2D0 * CI
     $ *(TMP1)+CI*(TMP13))+(TMP12*(-4D0/3D0)*(+1D0/2D0 * CI*(TMP13)+CI
     $ *(TMP1))+2D0/1D0 * CI*(TMP2*TMP3))))+(P1(3)*(TMP14*(+CI*(TMP13
     $ +TMP1))-CI*(TMP2*TMP10))+(P2(3)*(TMP11*(+CI*(TMP0+TMP12))-CI
     $ *(TMP2*TMP9))+(V1(6)*(TMP10*(+CI*(TMP0+TMP12))-CI*(TMP3*TMP14))
     $ +V2(6)*(TMP9*(+CI*(TMP13+TMP1))-CI*(TMP3*TMP11))))))+P3(3)
     $ *(P1(0)*(TMP14*(+CI*(TMP13+TMP1))-CI*(TMP2*TMP10))+(P2(0)
     $ *(TMP11*(+CI*(TMP0+TMP12))-CI*(TMP2*TMP9))+(V1(3)*(TMP10*(+CI
     $ *(TMP0+TMP12))-CI*(TMP3*TMP14))+V2(3)*(TMP9*(+CI*(TMP13+TMP1))
     $ -CI*(TMP3*TMP11))))))+(P1(0)*(V2(6)*(-1D0)*(+CI*(TMP13+TMP1))
     $ +CI*(P2(3)*TMP2))+(P1(3)*(V2(3)*(-1D0)*(+CI*(TMP13+TMP1))+CI
     $ *(P2(0)*TMP2))+(V1(3)*(P2(3)*(-1D0)*(+CI*(TMP0+TMP12))+CI*(V2(6)
     $ *TMP3))+V1(6)*(P2(0)*(-1D0)*(+CI*(TMP0+TMP12))+CI*(V2(3)*TMP3)))
     $ )))
      T3(7)= DENOM*(OM3*(P3(0)*(P3(1)*(OM3*(TMP15*(TMP0*2D0/3D0*(+CI
     $ *(TMP13+TMP1))+(TMP12*2D0/3D0*(+CI*(TMP13+TMP1))-2D0/3D0 * CI
     $ *(TMP2*TMP3)))+(TMP10*(TMP11*(-4D0/3D0)*(+CI*(TMP0+TMP12))+4D0
     $ /3D0 * CI*(TMP2*TMP9))+TMP14*(TMP9*(-4D0/3D0)*(+CI*(TMP13+TMP1))
     $ +4D0/3D0 * CI*(TMP3*TMP11))))+(TMP0*(-4D0/3D0)*(+3D0/2D0 * CI
     $ *(TMP1)+CI*(TMP13))+(TMP12*(-4D0/3D0)*(+1D0/2D0 * CI*(TMP13)+CI
     $ *(TMP1))+2D0/1D0 * CI*(TMP2*TMP3))))+(P1(1)*(TMP14*(+CI*(TMP13
     $ +TMP1))-CI*(TMP2*TMP10))+(P2(1)*(TMP11*(+CI*(TMP0+TMP12))-CI
     $ *(TMP2*TMP9))+(V1(4)*(TMP10*(+CI*(TMP0+TMP12))-CI*(TMP3*TMP14))
     $ +V2(4)*(TMP9*(+CI*(TMP13+TMP1))-CI*(TMP3*TMP11))))))+P3(1)
     $ *(P1(0)*(TMP14*(+CI*(TMP13+TMP1))-CI*(TMP2*TMP10))+(P2(0)
     $ *(TMP11*(+CI*(TMP0+TMP12))-CI*(TMP2*TMP9))+(V1(3)*(TMP10*(+CI
     $ *(TMP0+TMP12))-CI*(TMP3*TMP14))+V2(3)*(TMP9*(+CI*(TMP13+TMP1))
     $ -CI*(TMP3*TMP11))))))+(P1(0)*(V2(4)*(-1D0)*(+CI*(TMP13+TMP1))
     $ +CI*(P2(1)*TMP2))+(P1(1)*(V2(3)*(-1D0)*(+CI*(TMP13+TMP1))+CI
     $ *(P2(0)*TMP2))+(V1(3)*(P2(1)*(-1D0)*(+CI*(TMP0+TMP12))+CI*(V2(4)
     $ *TMP3))+V1(4)*(P2(0)*(-1D0)*(+CI*(TMP0+TMP12))+CI*(V2(3)*TMP3)))
     $ )))
      T3(8)= DENOM*(-2D0)*(OM3*(P3(1)*(P3(1)*(OM3*(TMP15*(TMP0*(-1D0
     $ /3D0)*(+CI*(TMP13+TMP1))+(TMP12*(-1D0/3D0)*(+CI*(TMP13+TMP1))
     $ +1D0/3D0 * CI*(TMP2*TMP3)))+(TMP10*(TMP11*2D0/3D0*(+CI*(TMP0
     $ +TMP12))-2D0/3D0 * CI*(TMP2*TMP9))+TMP14*(TMP9*2D0/3D0*(+CI
     $ *(TMP13+TMP1))-2D0/3D0 * CI*(TMP3*TMP11))))+(TMP0*2D0/3D0*(+3D0
     $ /2D0 * CI*(TMP1)+CI*(TMP13))+(TMP12*2D0/3D0*(+1D0/2D0 * CI
     $ *(TMP13)+CI*(TMP1))-1D0/1D0 * CI*(TMP2*TMP3))))+(P1(1)*(TMP14*(
     $ -1D0)*(+CI*(TMP13+TMP1))+CI*(TMP2*TMP10))+(P2(1)*(TMP11*(-1D0)
     $ *(+CI*(TMP0+TMP12))+CI*(TMP2*TMP9))+(V1(4)*(TMP10*(-1D0)*(+CI
     $ *(TMP0+TMP12))+CI*(TMP3*TMP14))+V2(4)*(TMP9*(-1D0)*(+CI*(TMP13
     $ +TMP1))+CI*(TMP3*TMP11))))))+(TMP15*(TMP0*1D0/6D0*(+CI*(TMP13
     $ +TMP1))+(TMP12*1D0/6D0*(+CI*(TMP13+TMP1))-1D0/6D0 * CI*(TMP2
     $ *TMP3)))+(TMP10*(TMP11*(-1D0/3D0)*(+CI*(TMP0+TMP12))+1D0/3D0 *
     $  CI*(TMP2*TMP9))+TMP14*(TMP9*(-1D0/3D0)*(+CI*(TMP13+TMP1))+1D0
     $ /3D0 * CI*(TMP3*TMP11)))))+(P1(1)*(V2(4)*(+CI*(TMP13+TMP1))-CI
     $ *(P2(1)*TMP2))+(V1(4)*(P2(1)*(+CI*(TMP0+TMP12))-CI*(V2(4)*TMP3))
     $ +(TMP0*1D0/2D0*(+CI*(TMP1)+1D0/3D0 * CI*(TMP13))+(-1D0/2D0 * CI
     $ *(TMP2*TMP3)+TMP12*1D0/6D0*(-1D0/1D0 * CI*(TMP13)+CI*(TMP1))))))
     $ )
      T3(9)= DENOM*(OM3*(P3(1)*(P3(2)*(OM3*(TMP15*(TMP0*2D0/3D0*(+CI
     $ *(TMP13+TMP1))+(TMP12*2D0/3D0*(+CI*(TMP13+TMP1))-2D0/3D0 * CI
     $ *(TMP2*TMP3)))+(TMP10*(TMP11*(-4D0/3D0)*(+CI*(TMP0+TMP12))+4D0
     $ /3D0 * CI*(TMP2*TMP9))+TMP14*(TMP9*(-4D0/3D0)*(+CI*(TMP13+TMP1))
     $ +4D0/3D0 * CI*(TMP3*TMP11))))+(TMP0*(-4D0/3D0)*(+3D0/2D0 * CI
     $ *(TMP1)+CI*(TMP13))+(TMP12*(-4D0/3D0)*(+1D0/2D0 * CI*(TMP13)+CI
     $ *(TMP1))+2D0/1D0 * CI*(TMP2*TMP3))))+(P1(2)*(TMP14*(+CI*(TMP13
     $ +TMP1))-CI*(TMP2*TMP10))+(P2(2)*(TMP11*(+CI*(TMP0+TMP12))-CI
     $ *(TMP2*TMP9))+(V1(5)*(TMP10*(+CI*(TMP0+TMP12))-CI*(TMP3*TMP14))
     $ +V2(5)*(TMP9*(+CI*(TMP13+TMP1))-CI*(TMP3*TMP11))))))+P3(2)
     $ *(P1(1)*(TMP14*(+CI*(TMP13+TMP1))-CI*(TMP2*TMP10))+(P2(1)
     $ *(TMP11*(+CI*(TMP0+TMP12))-CI*(TMP2*TMP9))+(V1(4)*(TMP10*(+CI
     $ *(TMP0+TMP12))-CI*(TMP3*TMP14))+V2(4)*(TMP9*(+CI*(TMP13+TMP1))
     $ -CI*(TMP3*TMP11))))))+(P1(1)*(V2(5)*(-1D0)*(+CI*(TMP13+TMP1))
     $ +CI*(P2(2)*TMP2))+(P1(2)*(V2(4)*(-1D0)*(+CI*(TMP13+TMP1))+CI
     $ *(P2(1)*TMP2))+(V1(4)*(P2(2)*(-1D0)*(+CI*(TMP0+TMP12))+CI*(V2(5)
     $ *TMP3))+V1(5)*(P2(1)*(-1D0)*(+CI*(TMP0+TMP12))+CI*(V2(4)*TMP3)))
     $ )))
      T3(10)= DENOM*(OM3*(P3(1)*(P3(3)*(OM3*(TMP15*(TMP0*2D0/3D0*(+CI
     $ *(TMP13+TMP1))+(TMP12*2D0/3D0*(+CI*(TMP13+TMP1))-2D0/3D0 * CI
     $ *(TMP2*TMP3)))+(TMP10*(TMP11*(-4D0/3D0)*(+CI*(TMP0+TMP12))+4D0
     $ /3D0 * CI*(TMP2*TMP9))+TMP14*(TMP9*(-4D0/3D0)*(+CI*(TMP13+TMP1))
     $ +4D0/3D0 * CI*(TMP3*TMP11))))+(TMP0*(-4D0/3D0)*(+3D0/2D0 * CI
     $ *(TMP1)+CI*(TMP13))+(TMP12*(-4D0/3D0)*(+1D0/2D0 * CI*(TMP13)+CI
     $ *(TMP1))+2D0/1D0 * CI*(TMP2*TMP3))))+(P1(3)*(TMP14*(+CI*(TMP13
     $ +TMP1))-CI*(TMP2*TMP10))+(P2(3)*(TMP11*(+CI*(TMP0+TMP12))-CI
     $ *(TMP2*TMP9))+(V1(6)*(TMP10*(+CI*(TMP0+TMP12))-CI*(TMP3*TMP14))
     $ +V2(6)*(TMP9*(+CI*(TMP13+TMP1))-CI*(TMP3*TMP11))))))+P3(3)
     $ *(P1(1)*(TMP14*(+CI*(TMP13+TMP1))-CI*(TMP2*TMP10))+(P2(1)
     $ *(TMP11*(+CI*(TMP0+TMP12))-CI*(TMP2*TMP9))+(V1(4)*(TMP10*(+CI
     $ *(TMP0+TMP12))-CI*(TMP3*TMP14))+V2(4)*(TMP9*(+CI*(TMP13+TMP1))
     $ -CI*(TMP3*TMP11))))))+(P1(1)*(V2(6)*(-1D0)*(+CI*(TMP13+TMP1))
     $ +CI*(P2(3)*TMP2))+(P1(3)*(V2(4)*(-1D0)*(+CI*(TMP13+TMP1))+CI
     $ *(P2(1)*TMP2))+(V1(4)*(P2(3)*(-1D0)*(+CI*(TMP0+TMP12))+CI*(V2(6)
     $ *TMP3))+V1(6)*(P2(1)*(-1D0)*(+CI*(TMP0+TMP12))+CI*(V2(4)*TMP3)))
     $ )))
      T3(11)= DENOM*(OM3*(P3(0)*(P3(2)*(OM3*(TMP15*(TMP0*2D0/3D0*(+CI
     $ *(TMP13+TMP1))+(TMP12*2D0/3D0*(+CI*(TMP13+TMP1))-2D0/3D0 * CI
     $ *(TMP2*TMP3)))+(TMP10*(TMP11*(-4D0/3D0)*(+CI*(TMP0+TMP12))+4D0
     $ /3D0 * CI*(TMP2*TMP9))+TMP14*(TMP9*(-4D0/3D0)*(+CI*(TMP13+TMP1))
     $ +4D0/3D0 * CI*(TMP3*TMP11))))+(TMP0*(-4D0/3D0)*(+3D0/2D0 * CI
     $ *(TMP1)+CI*(TMP13))+(TMP12*(-4D0/3D0)*(+1D0/2D0 * CI*(TMP13)+CI
     $ *(TMP1))+2D0/1D0 * CI*(TMP2*TMP3))))+(P1(2)*(TMP14*(+CI*(TMP13
     $ +TMP1))-CI*(TMP2*TMP10))+(P2(2)*(TMP11*(+CI*(TMP0+TMP12))-CI
     $ *(TMP2*TMP9))+(V1(5)*(TMP10*(+CI*(TMP0+TMP12))-CI*(TMP3*TMP14))
     $ +V2(5)*(TMP9*(+CI*(TMP13+TMP1))-CI*(TMP3*TMP11))))))+P3(2)
     $ *(P1(0)*(TMP14*(+CI*(TMP13+TMP1))-CI*(TMP2*TMP10))+(P2(0)
     $ *(TMP11*(+CI*(TMP0+TMP12))-CI*(TMP2*TMP9))+(V1(3)*(TMP10*(+CI
     $ *(TMP0+TMP12))-CI*(TMP3*TMP14))+V2(3)*(TMP9*(+CI*(TMP13+TMP1))
     $ -CI*(TMP3*TMP11))))))+(P1(0)*(V2(5)*(-1D0)*(+CI*(TMP13+TMP1))
     $ +CI*(P2(2)*TMP2))+(P1(2)*(V2(3)*(-1D0)*(+CI*(TMP13+TMP1))+CI
     $ *(P2(0)*TMP2))+(V1(3)*(P2(2)*(-1D0)*(+CI*(TMP0+TMP12))+CI*(V2(5)
     $ *TMP3))+V1(5)*(P2(0)*(-1D0)*(+CI*(TMP0+TMP12))+CI*(V2(3)*TMP3)))
     $ )))
      T3(12)= DENOM*(OM3*(P3(1)*(P3(2)*(OM3*(TMP15*(TMP0*2D0/3D0*(+CI
     $ *(TMP13+TMP1))+(TMP12*2D0/3D0*(+CI*(TMP13+TMP1))-2D0/3D0 * CI
     $ *(TMP2*TMP3)))+(TMP10*(TMP11*(-4D0/3D0)*(+CI*(TMP0+TMP12))+4D0
     $ /3D0 * CI*(TMP2*TMP9))+TMP14*(TMP9*(-4D0/3D0)*(+CI*(TMP13+TMP1))
     $ +4D0/3D0 * CI*(TMP3*TMP11))))+(TMP0*(-4D0/3D0)*(+3D0/2D0 * CI
     $ *(TMP1)+CI*(TMP13))+(TMP12*(-4D0/3D0)*(+1D0/2D0 * CI*(TMP13)+CI
     $ *(TMP1))+2D0/1D0 * CI*(TMP2*TMP3))))+(P1(2)*(TMP14*(+CI*(TMP13
     $ +TMP1))-CI*(TMP2*TMP10))+(P2(2)*(TMP11*(+CI*(TMP0+TMP12))-CI
     $ *(TMP2*TMP9))+(V1(5)*(TMP10*(+CI*(TMP0+TMP12))-CI*(TMP3*TMP14))
     $ +V2(5)*(TMP9*(+CI*(TMP13+TMP1))-CI*(TMP3*TMP11))))))+P3(2)
     $ *(P1(1)*(TMP14*(+CI*(TMP13+TMP1))-CI*(TMP2*TMP10))+(P2(1)
     $ *(TMP11*(+CI*(TMP0+TMP12))-CI*(TMP2*TMP9))+(V1(4)*(TMP10*(+CI
     $ *(TMP0+TMP12))-CI*(TMP3*TMP14))+V2(4)*(TMP9*(+CI*(TMP13+TMP1))
     $ -CI*(TMP3*TMP11))))))+(P1(1)*(V2(5)*(-1D0)*(+CI*(TMP13+TMP1))
     $ +CI*(P2(2)*TMP2))+(P1(2)*(V2(4)*(-1D0)*(+CI*(TMP13+TMP1))+CI
     $ *(P2(1)*TMP2))+(V1(4)*(P2(2)*(-1D0)*(+CI*(TMP0+TMP12))+CI*(V2(5)
     $ *TMP3))+V1(5)*(P2(1)*(-1D0)*(+CI*(TMP0+TMP12))+CI*(V2(4)*TMP3)))
     $ )))
      T3(13)= DENOM*(-2D0)*(OM3*(P3(2)*(P3(2)*(OM3*(TMP15*(TMP0*(-1D0
     $ /3D0)*(+CI*(TMP13+TMP1))+(TMP12*(-1D0/3D0)*(+CI*(TMP13+TMP1))
     $ +1D0/3D0 * CI*(TMP2*TMP3)))+(TMP10*(TMP11*2D0/3D0*(+CI*(TMP0
     $ +TMP12))-2D0/3D0 * CI*(TMP2*TMP9))+TMP14*(TMP9*2D0/3D0*(+CI
     $ *(TMP13+TMP1))-2D0/3D0 * CI*(TMP3*TMP11))))+(TMP0*2D0/3D0*(+3D0
     $ /2D0 * CI*(TMP1)+CI*(TMP13))+(TMP12*2D0/3D0*(+1D0/2D0 * CI
     $ *(TMP13)+CI*(TMP1))-1D0/1D0 * CI*(TMP2*TMP3))))+(P1(2)*(TMP14*(
     $ -1D0)*(+CI*(TMP13+TMP1))+CI*(TMP2*TMP10))+(P2(2)*(TMP11*(-1D0)
     $ *(+CI*(TMP0+TMP12))+CI*(TMP2*TMP9))+(V1(5)*(TMP10*(-1D0)*(+CI
     $ *(TMP0+TMP12))+CI*(TMP3*TMP14))+V2(5)*(TMP9*(-1D0)*(+CI*(TMP13
     $ +TMP1))+CI*(TMP3*TMP11))))))+(TMP15*(TMP0*1D0/6D0*(+CI*(TMP13
     $ +TMP1))+(TMP12*1D0/6D0*(+CI*(TMP13+TMP1))-1D0/6D0 * CI*(TMP2
     $ *TMP3)))+(TMP10*(TMP11*(-1D0/3D0)*(+CI*(TMP0+TMP12))+1D0/3D0 *
     $  CI*(TMP2*TMP9))+TMP14*(TMP9*(-1D0/3D0)*(+CI*(TMP13+TMP1))+1D0
     $ /3D0 * CI*(TMP3*TMP11)))))+(P1(2)*(V2(5)*(+CI*(TMP13+TMP1))-CI
     $ *(P2(2)*TMP2))+(V1(5)*(P2(2)*(+CI*(TMP0+TMP12))-CI*(V2(5)*TMP3))
     $ +(TMP0*1D0/2D0*(+CI*(TMP1)+1D0/3D0 * CI*(TMP13))+(-1D0/2D0 * CI
     $ *(TMP2*TMP3)+TMP12*1D0/6D0*(-1D0/1D0 * CI*(TMP13)+CI*(TMP1))))))
     $ )
      T3(14)= DENOM*(OM3*(P3(2)*(P3(3)*(OM3*(TMP15*(TMP0*2D0/3D0*(+CI
     $ *(TMP13+TMP1))+(TMP12*2D0/3D0*(+CI*(TMP13+TMP1))-2D0/3D0 * CI
     $ *(TMP2*TMP3)))+(TMP10*(TMP11*(-4D0/3D0)*(+CI*(TMP0+TMP12))+4D0
     $ /3D0 * CI*(TMP2*TMP9))+TMP14*(TMP9*(-4D0/3D0)*(+CI*(TMP13+TMP1))
     $ +4D0/3D0 * CI*(TMP3*TMP11))))+(TMP0*(-4D0/3D0)*(+3D0/2D0 * CI
     $ *(TMP1)+CI*(TMP13))+(TMP12*(-4D0/3D0)*(+1D0/2D0 * CI*(TMP13)+CI
     $ *(TMP1))+2D0/1D0 * CI*(TMP2*TMP3))))+(P1(3)*(TMP14*(+CI*(TMP13
     $ +TMP1))-CI*(TMP2*TMP10))+(P2(3)*(TMP11*(+CI*(TMP0+TMP12))-CI
     $ *(TMP2*TMP9))+(V1(6)*(TMP10*(+CI*(TMP0+TMP12))-CI*(TMP3*TMP14))
     $ +V2(6)*(TMP9*(+CI*(TMP13+TMP1))-CI*(TMP3*TMP11))))))+P3(3)
     $ *(P1(2)*(TMP14*(+CI*(TMP13+TMP1))-CI*(TMP2*TMP10))+(P2(2)
     $ *(TMP11*(+CI*(TMP0+TMP12))-CI*(TMP2*TMP9))+(V1(5)*(TMP10*(+CI
     $ *(TMP0+TMP12))-CI*(TMP3*TMP14))+V2(5)*(TMP9*(+CI*(TMP13+TMP1))
     $ -CI*(TMP3*TMP11))))))+(P1(2)*(V2(6)*(-1D0)*(+CI*(TMP13+TMP1))
     $ +CI*(P2(3)*TMP2))+(P1(3)*(V2(5)*(-1D0)*(+CI*(TMP13+TMP1))+CI
     $ *(P2(2)*TMP2))+(V1(5)*(P2(3)*(-1D0)*(+CI*(TMP0+TMP12))+CI*(V2(6)
     $ *TMP3))+V1(6)*(P2(2)*(-1D0)*(+CI*(TMP0+TMP12))+CI*(V2(5)*TMP3)))
     $ )))
      T3(15)= DENOM*(OM3*(P3(0)*(P3(3)*(OM3*(TMP15*(TMP0*2D0/3D0*(+CI
     $ *(TMP13+TMP1))+(TMP12*2D0/3D0*(+CI*(TMP13+TMP1))-2D0/3D0 * CI
     $ *(TMP2*TMP3)))+(TMP10*(TMP11*(-4D0/3D0)*(+CI*(TMP0+TMP12))+4D0
     $ /3D0 * CI*(TMP2*TMP9))+TMP14*(TMP9*(-4D0/3D0)*(+CI*(TMP13+TMP1))
     $ +4D0/3D0 * CI*(TMP3*TMP11))))+(TMP0*(-4D0/3D0)*(+3D0/2D0 * CI
     $ *(TMP1)+CI*(TMP13))+(TMP12*(-4D0/3D0)*(+1D0/2D0 * CI*(TMP13)+CI
     $ *(TMP1))+2D0/1D0 * CI*(TMP2*TMP3))))+(P1(3)*(TMP14*(+CI*(TMP13
     $ +TMP1))-CI*(TMP2*TMP10))+(P2(3)*(TMP11*(+CI*(TMP0+TMP12))-CI
     $ *(TMP2*TMP9))+(V1(6)*(TMP10*(+CI*(TMP0+TMP12))-CI*(TMP3*TMP14))
     $ +V2(6)*(TMP9*(+CI*(TMP13+TMP1))-CI*(TMP3*TMP11))))))+P3(3)
     $ *(P1(0)*(TMP14*(+CI*(TMP13+TMP1))-CI*(TMP2*TMP10))+(P2(0)
     $ *(TMP11*(+CI*(TMP0+TMP12))-CI*(TMP2*TMP9))+(V1(3)*(TMP10*(+CI
     $ *(TMP0+TMP12))-CI*(TMP3*TMP14))+V2(3)*(TMP9*(+CI*(TMP13+TMP1))
     $ -CI*(TMP3*TMP11))))))+(P1(0)*(V2(6)*(-1D0)*(+CI*(TMP13+TMP1))
     $ +CI*(P2(3)*TMP2))+(P1(3)*(V2(3)*(-1D0)*(+CI*(TMP13+TMP1))+CI
     $ *(P2(0)*TMP2))+(V1(3)*(P2(3)*(-1D0)*(+CI*(TMP0+TMP12))+CI*(V2(6)
     $ *TMP3))+V1(6)*(P2(0)*(-1D0)*(+CI*(TMP0+TMP12))+CI*(V2(3)*TMP3)))
     $ )))
      T3(16)= DENOM*(OM3*(P3(1)*(P3(3)*(OM3*(TMP15*(TMP0*2D0/3D0*(+CI
     $ *(TMP13+TMP1))+(TMP12*2D0/3D0*(+CI*(TMP13+TMP1))-2D0/3D0 * CI
     $ *(TMP2*TMP3)))+(TMP10*(TMP11*(-4D0/3D0)*(+CI*(TMP0+TMP12))+4D0
     $ /3D0 * CI*(TMP2*TMP9))+TMP14*(TMP9*(-4D0/3D0)*(+CI*(TMP13+TMP1))
     $ +4D0/3D0 * CI*(TMP3*TMP11))))+(TMP0*(-4D0/3D0)*(+3D0/2D0 * CI
     $ *(TMP1)+CI*(TMP13))+(TMP12*(-4D0/3D0)*(+1D0/2D0 * CI*(TMP13)+CI
     $ *(TMP1))+2D0/1D0 * CI*(TMP2*TMP3))))+(P1(3)*(TMP14*(+CI*(TMP13
     $ +TMP1))-CI*(TMP2*TMP10))+(P2(3)*(TMP11*(+CI*(TMP0+TMP12))-CI
     $ *(TMP2*TMP9))+(V1(6)*(TMP10*(+CI*(TMP0+TMP12))-CI*(TMP3*TMP14))
     $ +V2(6)*(TMP9*(+CI*(TMP13+TMP1))-CI*(TMP3*TMP11))))))+P3(3)
     $ *(P1(1)*(TMP14*(+CI*(TMP13+TMP1))-CI*(TMP2*TMP10))+(P2(1)
     $ *(TMP11*(+CI*(TMP0+TMP12))-CI*(TMP2*TMP9))+(V1(4)*(TMP10*(+CI
     $ *(TMP0+TMP12))-CI*(TMP3*TMP14))+V2(4)*(TMP9*(+CI*(TMP13+TMP1))
     $ -CI*(TMP3*TMP11))))))+(P1(1)*(V2(6)*(-1D0)*(+CI*(TMP13+TMP1))
     $ +CI*(P2(3)*TMP2))+(P1(3)*(V2(4)*(-1D0)*(+CI*(TMP13+TMP1))+CI
     $ *(P2(1)*TMP2))+(V1(4)*(P2(3)*(-1D0)*(+CI*(TMP0+TMP12))+CI*(V2(6)
     $ *TMP3))+V1(6)*(P2(1)*(-1D0)*(+CI*(TMP0+TMP12))+CI*(V2(4)*TMP3)))
     $ )))
      T3(17)= DENOM*(OM3*(P3(2)*(P3(3)*(OM3*(TMP15*(TMP0*2D0/3D0*(+CI
     $ *(TMP13+TMP1))+(TMP12*2D0/3D0*(+CI*(TMP13+TMP1))-2D0/3D0 * CI
     $ *(TMP2*TMP3)))+(TMP10*(TMP11*(-4D0/3D0)*(+CI*(TMP0+TMP12))+4D0
     $ /3D0 * CI*(TMP2*TMP9))+TMP14*(TMP9*(-4D0/3D0)*(+CI*(TMP13+TMP1))
     $ +4D0/3D0 * CI*(TMP3*TMP11))))+(TMP0*(-4D0/3D0)*(+3D0/2D0 * CI
     $ *(TMP1)+CI*(TMP13))+(TMP12*(-4D0/3D0)*(+1D0/2D0 * CI*(TMP13)+CI
     $ *(TMP1))+2D0/1D0 * CI*(TMP2*TMP3))))+(P1(3)*(TMP14*(+CI*(TMP13
     $ +TMP1))-CI*(TMP2*TMP10))+(P2(3)*(TMP11*(+CI*(TMP0+TMP12))-CI
     $ *(TMP2*TMP9))+(V1(6)*(TMP10*(+CI*(TMP0+TMP12))-CI*(TMP3*TMP14))
     $ +V2(6)*(TMP9*(+CI*(TMP13+TMP1))-CI*(TMP3*TMP11))))))+P3(3)
     $ *(P1(2)*(TMP14*(+CI*(TMP13+TMP1))-CI*(TMP2*TMP10))+(P2(2)
     $ *(TMP11*(+CI*(TMP0+TMP12))-CI*(TMP2*TMP9))+(V1(5)*(TMP10*(+CI
     $ *(TMP0+TMP12))-CI*(TMP3*TMP14))+V2(5)*(TMP9*(+CI*(TMP13+TMP1))
     $ -CI*(TMP3*TMP11))))))+(P1(2)*(V2(6)*(-1D0)*(+CI*(TMP13+TMP1))
     $ +CI*(P2(3)*TMP2))+(P1(3)*(V2(5)*(-1D0)*(+CI*(TMP13+TMP1))+CI
     $ *(P2(2)*TMP2))+(V1(5)*(P2(3)*(-1D0)*(+CI*(TMP0+TMP12))+CI*(V2(6)
     $ *TMP3))+V1(6)*(P2(2)*(-1D0)*(+CI*(TMP0+TMP12))+CI*(V2(5)*TMP3)))
     $ )))
      T3(18)= DENOM*(-2D0)*(OM3*(P3(3)*(P3(3)*(OM3*(TMP15*(TMP0*(-1D0
     $ /3D0)*(+CI*(TMP13+TMP1))+(TMP12*(-1D0/3D0)*(+CI*(TMP13+TMP1))
     $ +1D0/3D0 * CI*(TMP2*TMP3)))+(TMP10*(TMP11*2D0/3D0*(+CI*(TMP0
     $ +TMP12))-2D0/3D0 * CI*(TMP2*TMP9))+TMP14*(TMP9*2D0/3D0*(+CI
     $ *(TMP13+TMP1))-2D0/3D0 * CI*(TMP3*TMP11))))+(TMP0*2D0/3D0*(+3D0
     $ /2D0 * CI*(TMP1)+CI*(TMP13))+(TMP12*2D0/3D0*(+1D0/2D0 * CI
     $ *(TMP13)+CI*(TMP1))-1D0/1D0 * CI*(TMP2*TMP3))))+(P1(3)*(TMP14*(
     $ -1D0)*(+CI*(TMP13+TMP1))+CI*(TMP2*TMP10))+(P2(3)*(TMP11*(-1D0)
     $ *(+CI*(TMP0+TMP12))+CI*(TMP2*TMP9))+(V1(6)*(TMP10*(-1D0)*(+CI
     $ *(TMP0+TMP12))+CI*(TMP3*TMP14))+V2(6)*(TMP9*(-1D0)*(+CI*(TMP13
     $ +TMP1))+CI*(TMP3*TMP11))))))+(TMP15*(TMP0*1D0/6D0*(+CI*(TMP13
     $ +TMP1))+(TMP12*1D0/6D0*(+CI*(TMP13+TMP1))-1D0/6D0 * CI*(TMP2
     $ *TMP3)))+(TMP10*(TMP11*(-1D0/3D0)*(+CI*(TMP0+TMP12))+1D0/3D0 *
     $  CI*(TMP2*TMP9))+TMP14*(TMP9*(-1D0/3D0)*(+CI*(TMP13+TMP1))+1D0
     $ /3D0 * CI*(TMP3*TMP11)))))+(P1(3)*(V2(6)*(+CI*(TMP13+TMP1))-CI
     $ *(P2(3)*TMP2))+(V1(6)*(P2(3)*(+CI*(TMP0+TMP12))-CI*(V2(6)*TMP3))
     $ +(TMP0*1D0/2D0*(+CI*(TMP1)+1D0/3D0 * CI*(TMP13))+(-1D0/2D0 * CI
     $ *(TMP2*TMP3)+TMP12*1D0/6D0*(-1D0/1D0 * CI*(TMP13)+CI*(TMP1))))))
     $ )
      END


