ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      REAL*16 MP__G
      COMMON/MP_STRONG/ MP__G

      COMPLEX*32 MP__GAL(2)
      COMMON/MP_WEAK/ MP__GAL

      COMPLEX*32 MP__MU_R
      COMMON/MP_RSCALE/ MP__MU_R


      REAL*16 MP__MDL_MT,MP__MDL_MW,MP__MDL_MZ,MP__MDL_MTA,MP__MDL_MB
     $ ,MP__MDL_MX0

      COMMON/MP_MASSES/ MP__MDL_MT,MP__MDL_MW,MP__MDL_MZ,MP__MDL_MTA
     $ ,MP__MDL_MB,MP__MDL_MX0


      REAL*16 MP__MDL_WX0,MP__MDL_WZ,MP__MDL_WW,MP__MDL_WT

      COMMON/MP_WIDTHS/ MP__MDL_WX0,MP__MDL_WZ,MP__MDL_WW,MP__MDL_WT


      COMPLEX*32 MP__R2_UUZ_V2,MP__R2_UUZ_V5,MP__R2_DXUW,MP__GC_5
     $ ,MP__GC_3005A,MP__GC_3005H2,MP__GC_3005H3,MP__GC_3005H4
     $ ,MP__GC_3007A,MP__GC_3007H2,MP__GC_3007H3,MP__GC_22,MP__GC_23
     $ ,MP__GC_24,MP__GC_47,MP__GC_3005H1,MP__GC_3007H1

      COMMON/MP_COUPLINGS/ MP__R2_UUZ_V2,MP__R2_UUZ_V5,MP__R2_DXUW
     $ ,MP__GC_5,MP__GC_3005A,MP__GC_3005H2,MP__GC_3005H3
     $ ,MP__GC_3005H4,MP__GC_3007A,MP__GC_3007H2,MP__GC_3007H3
     $ ,MP__GC_22,MP__GC_23,MP__GC_24,MP__GC_47,MP__GC_3005H1
     $ ,MP__GC_3007H1


