ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      DOUBLE PRECISION G
      COMMON/STRONG/ G

      DOUBLE COMPLEX GAL(2)
      COMMON/WEAK/ GAL

      DOUBLE PRECISION MU_R
      COMMON/RSCALE/ MU_R

      DOUBLE PRECISION NF
      PARAMETER(NF=4)

      DOUBLE PRECISION MDL_MT,MDL_MW,MDL_MZ,MDL_MTA,MDL_MHH,MDL_MB
     $ ,MDL_MH

      COMMON/MASSES/ MDL_MT,MDL_MW,MDL_MZ,MDL_MTA,MDL_MHH,MDL_MB,MDL_MH


      DOUBLE PRECISION MDL_WHH,MDL_WZ,MDL_WH,MDL_WW,MDL_WT

      COMMON/WIDTHS/ MDL_WHH,MDL_WZ,MDL_WH,MDL_WW,MDL_WT


      DOUBLE COMPLEX GC_13, GC_14, GC_15, GC_16, GC_17, GC_18, GC_33,
     $  GC_34, GC_35, GC_36, GC_37, GC_38, GC_45, GC_46, GC_77, GC_78,
     $  GC_79, GC_80

      COMMON/COUPLINGS/ GC_13, GC_14, GC_15, GC_16, GC_17, GC_18,
     $  GC_33, GC_34, GC_35, GC_36, GC_37, GC_38, GC_45, GC_46, GC_77,
     $  GC_78, GC_79, GC_80

