ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      WRITE(*,*)  ' External Params'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,*) 'mdl_cabi = ', MDL_CABI
      WRITE(*,*) 'mdl_rhoH = ', MDL_RHOH
      WRITE(*,*) 'mdl_Lambda = ', MDL_LAMBDA
      WRITE(*,*) 'mdl_fW = ', MDL_FW
      WRITE(*,*) 'mdl_fWW = ', MDL_FWW
      WRITE(*,*) 'mdl_fB = ', MDL_FB
      WRITE(*,*) 'mdl_fBB = ', MDL_FBB
      WRITE(*,*) 'aEWM1 = ', AEWM1
      WRITE(*,*) 'mdl_Gf = ', MDL_GF
      WRITE(*,*) 'aS = ', AS
      WRITE(*,*) 'mdl_ymb = ', MDL_YMB
      WRITE(*,*) 'mdl_ymt = ', MDL_YMT
      WRITE(*,*) 'mdl_ymtau = ', MDL_YMTAU
      WRITE(*,*) 'mdl_MZ = ', MDL_MZ
      WRITE(*,*) 'mdl_MTA = ', MDL_MTA
      WRITE(*,*) 'mdl_MT = ', MDL_MT
      WRITE(*,*) 'mdl_MB = ', MDL_MB
      WRITE(*,*) 'mdl_MH = ', MDL_MH
      WRITE(*,*) 'mdl_MHH = ', MDL_MHH
      WRITE(*,*) 'mdl_WZ = ', MDL_WZ
      WRITE(*,*) 'mdl_WW = ', MDL_WW
      WRITE(*,*) 'mdl_WT = ', MDL_WT
      WRITE(*,*) 'mdl_WH = ', MDL_WH
      WRITE(*,*) 'mdl_WHH = ', MDL_WHH
      WRITE(*,*)  ' Internal Params'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,*) 'mdl_cos__cabi = ', MDL_COS__CABI
      WRITE(*,*) 'mdl_CKM1x1 = ', MDL_CKM1X1
      WRITE(*,*) 'mdl_sin__cabi = ', MDL_SIN__CABI
      WRITE(*,*) 'mdl_CKM1x2 = ', MDL_CKM1X2
      WRITE(*,*) 'mdl_CKM2x1 = ', MDL_CKM2X1
      WRITE(*,*) 'mdl_CKM2x2 = ', MDL_CKM2X2
      WRITE(*,*) 'mdl_MZ__exp__2 = ', MDL_MZ__EXP__2
      WRITE(*,*) 'mdl_MZ__exp__4 = ', MDL_MZ__EXP__4
      WRITE(*,*) 'mdl_sqrt__2 = ', MDL_SQRT__2
      WRITE(*,*) 'mdl_Lambda__exp__2 = ', MDL_LAMBDA__EXP__2
      WRITE(*,*) 'mdl_MH__exp__2 = ', MDL_MH__EXP__2
      WRITE(*,*) 'mdl_complexi = ', MDL_COMPLEXI
      WRITE(*,*) 'mdl_conjg__CKM1x1 = ', MDL_CONJG__CKM1X1
      WRITE(*,*) 'mdl_conjg__CKM1x2 = ', MDL_CONJG__CKM1X2
      WRITE(*,*) 'mdl_conjg__CKM2x1 = ', MDL_CONJG__CKM2X1
      WRITE(*,*) 'mdl_conjg__CKM2x2 = ', MDL_CONJG__CKM2X2
      WRITE(*,*) 'mdl_aEW = ', MDL_AEW
      WRITE(*,*) 'mdl_MW = ', MDL_MW
      WRITE(*,*) 'mdl_sqrt__aEW = ', MDL_SQRT__AEW
      WRITE(*,*) 'mdl_ee = ', MDL_EE
      WRITE(*,*) 'mdl_MW__exp__2 = ', MDL_MW__EXP__2
      WRITE(*,*) 'mdl_sw2 = ', MDL_SW2
      WRITE(*,*) 'mdl_cw = ', MDL_CW
      WRITE(*,*) 'mdl_sqrt__sw2 = ', MDL_SQRT__SW2
      WRITE(*,*) 'mdl_sw = ', MDL_SW
      WRITE(*,*) 'mdl_g1 = ', MDL_G1
      WRITE(*,*) 'mdl_gw = ', MDL_GW
      WRITE(*,*) 'mdl_vev = ', MDL_VEV
      WRITE(*,*) 'mdl_gHWW = ', MDL_GHWW
      WRITE(*,*) 'mdl_gHWW1 = ', MDL_GHWW1
      WRITE(*,*) 'mdl_gHWW2 = ', MDL_GHWW2
      WRITE(*,*) 'mdl_cw__exp__2 = ', MDL_CW__EXP__2
      WRITE(*,*) 'mdl_gHZZ = ', MDL_GHZZ
      WRITE(*,*) 'mdl_sw__exp__2 = ', MDL_SW__EXP__2
      WRITE(*,*) 'mdl_gHZZ1 = ', MDL_GHZZ1
      WRITE(*,*) 'mdl_cw__exp__4 = ', MDL_CW__EXP__4
      WRITE(*,*) 'mdl_sw__exp__4 = ', MDL_SW__EXP__4
      WRITE(*,*) 'mdl_gHZZ2 = ', MDL_GHZZ2
      WRITE(*,*) 'mdl_vev__exp__2 = ', MDL_VEV__EXP__2
      WRITE(*,*) 'mdl_lam = ', MDL_LAM
      WRITE(*,*) 'mdl_yb = ', MDL_YB
      WRITE(*,*) 'mdl_yt = ', MDL_YT
      WRITE(*,*) 'mdl_ytau = ', MDL_YTAU
      WRITE(*,*) 'mdl_muH = ', MDL_MUH
      WRITE(*,*) 'mdl_I1a33 = ', MDL_I1A33
      WRITE(*,*) 'mdl_I2a33 = ', MDL_I2A33
      WRITE(*,*) 'mdl_I3a33 = ', MDL_I3A33
      WRITE(*,*) 'mdl_I4a33 = ', MDL_I4A33
      WRITE(*,*) 'mdl_ee__exp__2 = ', MDL_EE__EXP__2
      WRITE(*,*)  ' Internal Params evaluated point by point'
      WRITE(*,*)  ' ----------------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,*) 'mdl_sqrt__aS = ', MDL_SQRT__AS
      WRITE(*,*) 'mdl_G__exp__2 = ', MDL_G__EXP__2
