ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      WRITE(*,*)  ' Couplings of HC_UFO'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,2) 'GC_6 = ', GC_6
      WRITE(*,2) 'GC_7 = ', GC_7
      WRITE(*,2) 'GC_8 = ', GC_8
      WRITE(*,2) 'GC_10 = ', GC_10
      WRITE(*,2) 'GC_11 = ', GC_11
      WRITE(*,2) 'GC_12 = ', GC_12
      WRITE(*,2) 'GC_13 = ', GC_13
      WRITE(*,2) 'GC_62 = ', GC_62
      WRITE(*,2) 'GC_64 = ', GC_64
      WRITE(*,2) 'GC_65 = ', GC_65
      WRITE(*,2) 'GC_1 = ', GC_1
      WRITE(*,2) 'GC_2 = ', GC_2
      WRITE(*,2) 'GC_16 = ', GC_16
      WRITE(*,2) 'GC_66 = ', GC_66
      WRITE(*,2) 'GC_77 = ', GC_77
      WRITE(*,2) 'GC_78 = ', GC_78
      WRITE(*,2) 'GC_89 = ', GC_89
      WRITE(*,2) 'GC_90 = ', GC_90
      WRITE(*,2) 'GC_100 = ', GC_100
      WRITE(*,2) 'GC_38 = ', GC_38
      WRITE(*,2) 'GC_40 = ', GC_40
      WRITE(*,2) 'GC_42 = ', GC_42
      WRITE(*,2) 'GC_68 = ', GC_68
