C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     P(1,1)*P(2,1) - P(-1,1)*P(-1,1)*Metric(1,2) + P(1,2)*P(2,2) -
C      P(-1,2)*P(-1,2)*Metric(1,2)
C     
      SUBROUTINE VVS13_1(V2, S3, COUP, M1, W1,V1)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 V2(*)
      COMPLEX*16 DENOM
      COMPLEX*16 S3(*)
      COMPLEX*16 TMP1
      REAL*8 M1
      COMPLEX*16 P2(0:3)
      REAL*8 W1
      COMPLEX*16 TMP4
      COMPLEX*16 TMP5
      COMPLEX*16 V1(8)
      COMPLEX*16 P1(0:3)
      REAL*8 OM1
      COMPLEX*16 COUP
      COMPLEX*16 TMP7
      COMPLEX*16 TMP8
      OM1 = 0D0
      IF (M1.NE.0D0) OM1=1D0/M1**2
      P2(0) = V2(1)
      P2(1) = V2(2)
      P2(2) = V2(3)
      P2(3) = V2(4)
      V1(1) = +V2(1)+S3(1)
      V1(2) = +V2(2)+S3(2)
      V1(3) = +V2(3)+S3(3)
      V1(4) = +V2(4)+S3(4)
      P1(0) = -V1(1)
      P1(1) = -V1(2)
      P1(2) = -V1(3)
      P1(3) = -V1(4)
      TMP5 = (P2(0)*V2(5)-P2(1)*V2(6)-P2(2)*V2(7)-P2(3)*V2(8))
      TMP4 = (P1(0)*P1(0)-P1(1)*P1(1)-P1(2)*P1(2)-P1(3)*P1(3))
      TMP7 = (P2(0)*P2(0)-P2(1)*P2(1)-P2(2)*P2(2)-P2(3)*P2(3))
      TMP1 = (P1(0)*V2(5)-P1(1)*V2(6)-P1(2)*V2(7)-P1(3)*V2(8))
      TMP8 = (P1(0)*P2(0)-P1(1)*P2(1)-P1(2)*P2(2)-P1(3)*P2(3))
      DENOM = COUP/(P1(0)**2-P1(1)**2-P1(2)**2-P1(3)**2 - M1 * (M1 -CI
     $ * W1))
      V1(5)= DENOM*S3(5)*(P1(0)*(TMP1*(-1D0)*(+CI*(OM1*TMP7)+ CI)+CI
     $ *(OM1*TMP5*TMP8))+(V2(5)*(+CI*(TMP4+TMP7))-CI*(P2(0)*TMP5)))
      V1(6)= DENOM*S3(5)*(P1(1)*(TMP1*(-1D0)*(+CI*(OM1*TMP7)+ CI)+CI
     $ *(OM1*TMP5*TMP8))+(V2(6)*(+CI*(TMP4+TMP7))-CI*(P2(1)*TMP5)))
      V1(7)= DENOM*S3(5)*(P1(2)*(TMP1*(-1D0)*(+CI*(OM1*TMP7)+ CI)+CI
     $ *(OM1*TMP5*TMP8))+(V2(7)*(+CI*(TMP4+TMP7))-CI*(P2(2)*TMP5)))
      V1(8)= DENOM*S3(5)*(P1(3)*(TMP1*(-1D0)*(+CI*(OM1*TMP7)+ CI)+CI
     $ *(OM1*TMP5*TMP8))+(V2(8)*(+CI*(TMP4+TMP7))-CI*(P2(3)*TMP5)))
      END


