ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      WRITE(*,*)  ' Couplings of HC_UFO'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,2) 'GC_6 = ', GC_6
      WRITE(*,2) 'GC_7 = ', GC_7
      WRITE(*,2) 'GC_8 = ', GC_8
      WRITE(*,2) 'GC_10 = ', GC_10
      WRITE(*,2) 'GC_11 = ', GC_11
      WRITE(*,2) 'GC_12 = ', GC_12
      WRITE(*,2) 'GC_13 = ', GC_13
      WRITE(*,2) 'GC_62 = ', GC_62
      WRITE(*,2) 'GC_64 = ', GC_64
      WRITE(*,2) 'GC_65 = ', GC_65
      WRITE(*,2) 'GC_1 = ', GC_1
      WRITE(*,2) 'GC_2 = ', GC_2
      WRITE(*,2) 'GC_16 = ', GC_16
      WRITE(*,2) 'GC_66 = ', GC_66
      WRITE(*,2) 'GC_72 = ', GC_72
      WRITE(*,2) 'GC_73 = ', GC_73
      WRITE(*,2) 'GC_74 = ', GC_74
      WRITE(*,2) 'GC_75 = ', GC_75
      WRITE(*,2) 'GC_76 = ', GC_76
      WRITE(*,2) 'GC_77 = ', GC_77
      WRITE(*,2) 'GC_78 = ', GC_78
      WRITE(*,2) 'GC_89 = ', GC_89
      WRITE(*,2) 'GC_90 = ', GC_90
      WRITE(*,2) 'GC_99 = ', GC_99
      WRITE(*,2) 'GC_100 = ', GC_100
      WRITE(*,2) 'GC_101 = ', GC_101
      WRITE(*,2) 'GC_102 = ', GC_102
      WRITE(*,2) 'GC_105 = ', GC_105
      WRITE(*,2) 'GC_106 = ', GC_106
      WRITE(*,2) 'GC_107 = ', GC_107
      WRITE(*,2) 'GC_108 = ', GC_108
      WRITE(*,2) 'GC_109 = ', GC_109
      WRITE(*,2) 'GC_110 = ', GC_110
      WRITE(*,2) 'GC_38 = ', GC_38
      WRITE(*,2) 'GC_39 = ', GC_39
      WRITE(*,2) 'GC_40 = ', GC_40
      WRITE(*,2) 'GC_41 = ', GC_41
      WRITE(*,2) 'GC_42 = ', GC_42
      WRITE(*,2) 'GC_67 = ', GC_67
      WRITE(*,2) 'GC_68 = ', GC_68
      WRITE(*,2) 'GC_111 = ', GC_111
