ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      DOUBLE PRECISION G
      COMMON/STRONG/ G

      DOUBLE COMPLEX GAL(2)
      COMMON/WEAK/ GAL

      DOUBLE PRECISION MU_R
      COMMON/RSCALE/ MU_R

      DOUBLE PRECISION NF
      PARAMETER(NF=4)

      DOUBLE PRECISION MDL_MT,MDL_MW,MDL_MZ,MDL_MTA,MDL_MB,MDL_MX2
     $ ,MDL_MX0,MDL_MX1

      COMMON/MASSES/ MDL_MT,MDL_MW,MDL_MZ,MDL_MTA,MDL_MB,MDL_MX2
     $ ,MDL_MX0,MDL_MX1


      DOUBLE PRECISION MDL_WW,MDL_WT,MDL_WZ,MDL_WX0,MDL_WX1,MDL_WX2

      COMMON/WIDTHS/ MDL_WW,MDL_WT,MDL_WZ,MDL_WX0,MDL_WX1,MDL_WX2


      DOUBLE COMPLEX GC_10, GC_13, GC_62, GC_64, GC_1, GC_2, GC_3,
     $  GC_9, GC_16, GC_17, GC_19, GC_21, GC_22, GC_23, GC_24, GC_61,
     $  GC_66, GC_77, GC_78, GC_89, GC_90, GC_98, GC_100, GC_101,
     $  GC_102, GC_105, GC_106, GC_35, GC_38, GC_40, GC_42, GC_43,
     $  GC_45, GC_49, GC_56, GC_58, GC_68

      COMMON/COUPLINGS/ GC_10, GC_13, GC_62, GC_64, GC_1, GC_2, GC_3,
     $  GC_9, GC_16, GC_17, GC_19, GC_21, GC_22, GC_23, GC_24, GC_61,
     $  GC_66, GC_77, GC_78, GC_89, GC_90, GC_98, GC_100, GC_101,
     $  GC_102, GC_105, GC_106, GC_35, GC_38, GC_40, GC_42, GC_43,
     $  GC_45, GC_49, GC_56, GC_58, GC_68

