ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      WRITE(*,*)  ' Couplings of HC_UFO'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,2) 'GC_10 = ', GC_10
      WRITE(*,2) 'GC_13 = ', GC_13
      WRITE(*,2) 'GC_62 = ', GC_62
      WRITE(*,2) 'GC_64 = ', GC_64
      WRITE(*,2) 'GC_1 = ', GC_1
      WRITE(*,2) 'GC_2 = ', GC_2
      WRITE(*,2) 'GC_3 = ', GC_3
      WRITE(*,2) 'GC_9 = ', GC_9
      WRITE(*,2) 'GC_16 = ', GC_16
      WRITE(*,2) 'GC_17 = ', GC_17
      WRITE(*,2) 'GC_19 = ', GC_19
      WRITE(*,2) 'GC_21 = ', GC_21
      WRITE(*,2) 'GC_22 = ', GC_22
      WRITE(*,2) 'GC_23 = ', GC_23
      WRITE(*,2) 'GC_24 = ', GC_24
      WRITE(*,2) 'GC_61 = ', GC_61
      WRITE(*,2) 'GC_66 = ', GC_66
      WRITE(*,2) 'GC_77 = ', GC_77
      WRITE(*,2) 'GC_78 = ', GC_78
      WRITE(*,2) 'GC_89 = ', GC_89
      WRITE(*,2) 'GC_90 = ', GC_90
      WRITE(*,2) 'GC_98 = ', GC_98
      WRITE(*,2) 'GC_100 = ', GC_100
      WRITE(*,2) 'GC_101 = ', GC_101
      WRITE(*,2) 'GC_102 = ', GC_102
      WRITE(*,2) 'GC_105 = ', GC_105
      WRITE(*,2) 'GC_106 = ', GC_106
      WRITE(*,2) 'GC_35 = ', GC_35
      WRITE(*,2) 'GC_38 = ', GC_38
      WRITE(*,2) 'GC_40 = ', GC_40
      WRITE(*,2) 'GC_42 = ', GC_42
      WRITE(*,2) 'GC_43 = ', GC_43
      WRITE(*,2) 'GC_45 = ', GC_45
      WRITE(*,2) 'GC_49 = ', GC_49
      WRITE(*,2) 'GC_56 = ', GC_56
      WRITE(*,2) 'GC_58 = ', GC_58
      WRITE(*,2) 'GC_68 = ', GC_68
