ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      SUBROUTINE COUP1()

      IMPLICIT NONE
      INCLUDE 'model_functions.inc'

      DOUBLE PRECISION PI, ZERO
      PARAMETER  (PI=3.141592653589793D0)
      PARAMETER  (ZERO=0D0)
      INCLUDE 'input.inc'
      INCLUDE 'coupl.inc'
      GC_1 = -(MDL_EE*MDL_COMPLEXI)/3.000000D+00
      GC_2 = (2.000000D+00*MDL_EE*MDL_COMPLEXI)/3.000000D+00
      GC_3 = -(MDL_EE*MDL_COMPLEXI)
      GC_9 = -(MDL_CA*MDL_COMPLEXI*MDL_GHAA*MDL_KHAA)
      GC_16 = -(MDL_CA*MDL_COMPLEXI*MDL_GHZA*MDL_KHZA)
      GC_17 = MDL_AL*MDL_COMPLEXI*MDL_KLA
      GC_19 = -(MDL_BL*MDL_COMPLEXI*MDL_KLB)
      GC_21 = MDL_AD*MDL_COMPLEXI*MDL_KQA
      GC_22 = MDL_AU*MDL_COMPLEXI*MDL_KQA
      GC_23 = -(MDL_BD*MDL_COMPLEXI*MDL_KQB)
      GC_24 = -(MDL_BU*MDL_COMPLEXI*MDL_KQB)
      GC_61 = (MDL_COMPLEXI*MDL_GAAA*MDL_KAAA*MDL_SA)/2.000000D+00
      GC_66 = MDL_COMPLEXI*MDL_GAZA*MDL_KAZA*MDL_SA
      GC_77 = -(MDL_CW*MDL_EE*MDL_COMPLEXI)/(2.000000D+00*MDL_SW)
      GC_78 = (MDL_CW*MDL_EE*MDL_COMPLEXI)/(2.000000D+00*MDL_SW)
      GC_89 = -(MDL_EE*MDL_COMPLEXI*MDL_SW)/(6.000000D+00*MDL_CW)
      GC_90 = (MDL_EE*MDL_COMPLEXI*MDL_SW)/(2.000000D+00*MDL_CW)
      GC_98 = -6.000000D+00*MDL_CA__EXP__3*MDL_COMPLEXI*MDL_KSM
     $ *MDL_LAM*MDL_VEV
      GC_100 = MDL_CA*MDL_EE__EXP__2*MDL_COMPLEXI*MDL_KSM*MDL_VEV
     $ +(MDL_CA*MDL_CW__EXP__2*MDL_EE__EXP__2*MDL_COMPLEXI*MDL_KSM
     $ *MDL_VEV)/(2.000000D+00*MDL_SW__EXP__2)+(MDL_CA*MDL_EE__EXP__2
     $ *MDL_COMPLEXI*MDL_KSM*MDL_SW__EXP__2*MDL_VEV)/(2.000000D+00
     $ *MDL_CW__EXP__2)
      GC_101 = -((MDL_CA*MDL_COMPLEXI*MDL_KHBB*MDL_YB)/MDL_SQRT__2)
      GC_102 = (MDL_KABB*MDL_SA*MDL_YB)/MDL_SQRT__2
      GC_105 = -((MDL_CA*MDL_COMPLEXI*MDL_KHLL*MDL_YTAU)/MDL_SQRT__2)
      GC_106 = (MDL_KALL*MDL_SA*MDL_YTAU)/MDL_SQRT__2
      GC_35 = -((MDL_COMPLEXI*MDL_KG)/MDL_LAMBDA)
      GC_38 = -((MDL_CA*MDL_COMPLEXI*MDL_KHDA)/MDL_LAMBDA)
      END
