/********************************************************************
* tmp/classes/ClassesDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error tmp/classes/ClassesDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableClassesDict();
extern void G__cpp_setup_inheritanceClassesDict();
extern void G__cpp_setup_typetableClassesDict();
extern void G__cpp_setup_memvarClassesDict();
extern void G__cpp_setup_globalClassesDict();
extern void G__cpp_setup_memfuncClassesDict();
extern void G__cpp_setup_funcClassesDict();
extern void G__set_cpp_environmentClassesDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__ClassesDictLN_TClass;
extern G__linked_taginfo G__ClassesDictLN_TBuffer;
extern G__linked_taginfo G__ClassesDictLN_TMemberInspector;
extern G__linked_taginfo G__ClassesDictLN_TObject;
extern G__linked_taginfo G__ClassesDictLN_TNamed;
extern G__linked_taginfo G__ClassesDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__ClassesDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__ClassesDictLN_TObjArray;
extern G__linked_taginfo G__ClassesDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__ClassesDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__ClassesDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__ClassesDictLN_TTask;
extern G__linked_taginfo G__ClassesDictLN_maplETStringcOTStringcOlesslETStringgRcOallocatorlEpairlEconstsPTStringcOTStringgRsPgRsPgR;
extern G__linked_taginfo G__ClassesDictLN_TFolder;
extern G__linked_taginfo G__ClassesDictLN_ExRootTask;
extern G__linked_taginfo G__ClassesDictLN_ExRootResult;
extern G__linked_taginfo G__ClassesDictLN_ExRootTreeBranch;
extern G__linked_taginfo G__ClassesDictLN_ExRootTreeWriter;
extern G__linked_taginfo G__ClassesDictLN_DelphesFactory;
extern G__linked_taginfo G__ClassesDictLN_DelphesModule;
extern G__linked_taginfo G__ClassesDictLN_Candidate;
extern G__linked_taginfo G__ClassesDictLN_setlETObjectmUcOlesslETObjectmUgRcOallocatorlETObjectmUgRsPgR;
extern G__linked_taginfo G__ClassesDictLN_TRef;
extern G__linked_taginfo G__ClassesDictLN_TRefArray;
extern G__linked_taginfo G__ClassesDictLN_CompBase;
extern G__linked_taginfo G__ClassesDictLN_SortableObject;
extern G__linked_taginfo G__ClassesDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__ClassesDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__ClassesDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__ClassesDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__ClassesDictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__ClassesDictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__ClassesDictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__ClassesDictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__ClassesDictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__ClassesDictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__ClassesDictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__ClassesDictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__ClassesDictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__ClassesDictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__ClassesDictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__ClassesDictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__ClassesDictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__ClassesDictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__ClassesDictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__ClassesDictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__ClassesDictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__ClassesDictLN_TLorentzVector;
extern G__linked_taginfo G__ClassesDictLN_Event;
extern G__linked_taginfo G__ClassesDictLN_LHCOEvent;
extern G__linked_taginfo G__ClassesDictLN_LHEFEvent;
extern G__linked_taginfo G__ClassesDictLN_LHEFWeight;
extern G__linked_taginfo G__ClassesDictLN_HepMCEvent;
extern G__linked_taginfo G__ClassesDictLN_GenParticle;
extern G__linked_taginfo G__ClassesDictLN_Vertex;
extern G__linked_taginfo G__ClassesDictLN_MissingET;
extern G__linked_taginfo G__ClassesDictLN_ScalarHT;
extern G__linked_taginfo G__ClassesDictLN_Rho;
extern G__linked_taginfo G__ClassesDictLN_Weight;
extern G__linked_taginfo G__ClassesDictLN_Photon;
extern G__linked_taginfo G__ClassesDictLN_Electron;
extern G__linked_taginfo G__ClassesDictLN_Muon;
extern G__linked_taginfo G__ClassesDictLN_Jet;
extern G__linked_taginfo G__ClassesDictLN_Track;
extern G__linked_taginfo G__ClassesDictLN_Tower;
extern G__linked_taginfo G__ClassesDictLN_HectorHit;
extern G__linked_taginfo G__ClassesDictLN_pairlEfloatcOfloatgR;
extern G__linked_taginfo G__ClassesDictLN_vectorlEpairlEfloatcOfloatgRcOallocatorlEpairlEfloatcOfloatgRsPgRsPgR;
extern G__linked_taginfo G__ClassesDictLN_reverse_iteratorlEvectorlEpairlEfloatcOfloatgRcOallocatorlEpairlEfloatcOfloatgRsPgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
