C     Diagram 1, Amplitude 1
      DATA MAPCONFIG(   1)/   1/
      DATA (IFOREST(I, -1,   1),I=1,2)/  5,  4/
      DATA SPROP(  -1,   1)/      23/
      DATA (IFOREST(I, -2,   1),I=1,2)/  6,  3/
      DATA SPROP(  -2,   1)/      25/
      DATA (IFOREST(I, -3,   1),I=1,2)/ -1, -2/
      DATA SPROP(  -3,   1)/      23/
C     Diagram 2, Amplitude 2
      DATA MAPCONFIG(   2)/   2/
      DATA (IFOREST(I, -1,   2),I=1,2)/  5,  4/
      DATA SPROP(  -1,   2)/      23/
      DATA (IFOREST(I, -2,   2),I=1,2)/  6, -1/
      DATA SPROP(  -2,   2)/      25/
      DATA (IFOREST(I, -3,   2),I=1,2)/ -2,  3/
      DATA SPROP(  -3,   2)/      23/
C     Diagram 3, Amplitude 3
      DATA MAPCONFIG(   3)/   3/
      DATA (IFOREST(I, -1,   3),I=1,2)/  5,  4/
      DATA SPROP(  -1,   3)/      23/
      DATA (IFOREST(I, -2,   3),I=1,2)/ -1,  3/
      DATA SPROP(  -2,   3)/      25/
      DATA (IFOREST(I, -3,   3),I=1,2)/  6, -2/
      DATA SPROP(  -3,   3)/      23/
C     Number of configs
      DATA MAPCONFIG(0)/   3/
